Translation for Bed
pmmp/PocketMine-MP pull request #103
Opened 2016-11-14 21:11 UTC by L3ice

Added the use of the built-in translation from mcpe.

2016-11-14 21:40 UTC, robske110 requested changes
You also need to include this in the PM translations, in order to not break force-language

2016-11-15 06:28 UTC, SOF3 requested changes
As @robske110 mentioned.

2016-12-01 12:30 UTC, dktapps submitted a review, later dismissed

2016-12-01 12:30 UTC, dktapps commented on src/pocketmine/block/Bed.php
> +					$player->sendMessage(new TranslationContainer(TextFormat::GRAY . "%tile.bed.notValid"));
In the game files, this is actually "Your home bed was missing or obstructed". I don't think this is correct.

2016-12-01 21:39 UTC, robske110 commented
I qoute:
@robske110 suggested changes ? days ago
You also need to include this in the PM translations, in order to not break force-language
 @SOF3	SOF3 requested changes 17 days ago
As @robske110 mentioned.

2016-12-01 21:46 UTC, L3ice commented
I think they know that...

2017-02-15 14:59 UTC, dktapps commented
Merged changes in the referenced commit.

2017-02-15 14:59 UTC, closed without merging