Made setLore() return Item being modified
pmmp/PocketMine-MP pull request #1120
Opened 2017-06-20 19:03 UTC by jasonwynn10

## Introduction

setLore() does not return the modified Item instance
### Relevant issues

## Changes
### API changes

Item::setLore() now returns Item
### Behavioural changes

No changes
## Backwards compatibility

Full compatability
## Follow-up

None
## Tests

Untested, but should not effect anything due to the returned value not being used by the core.

2017-06-20 19:17 UTC, Sandertv approved these changes
Good idea, matches with the other set functions from items. This should make life a lot easier.

2017-06-20 19:24 UTC, dktapps commented
For reference, this is called fluency, not concurrency.

2017-06-20 19:39 UTC, matcracker requested changes
Read my comment

2017-06-20 19:42 UTC, TheDiamondYT1 commented
@matcracker 
```php
$item = Item::get(Item::GRASS);
$item->setLore(["Lore"])->setCustomName("Lol");
```
```

2017-06-20 19:49 UTC, matcracker commented
@TheDiamondYT1 Obviously the gives null...
You should do in this way (remember that is OOP) :
```
$item = Item::get(Item::GRASS);
$item->setLore(["Description"]);
$item->setCustomName("CustomName");
$item->setCount(64);
```

2017-06-20 19:52 UTC, TheDiamondYT1 commented
@matcracker Of course you can. You can also do it this way:
```php
// mlg performance
die();
```
As @dktapps mentioned, [it's called fluency](https://en.m.wikipedia.org/wiki/Fluent_interface).

2017-06-21 15:26 UTC, jasonwynn10 commented
If all is good, can this be merged? @dktapps

2017-06-21 15:29 UTC, jasonwynn10 commented
@matcracker 
I found the non-fluent method to be annoying due to this:
```
$inv = [
Item::get(Item::ARROW)->setCustomName("Name"),
Item::get(Item::WOOL,7,1)->setLore(["Return"])
]
```
this outputs an error

2017-06-22 08:03 UTC, dktapps commented on src/pocketmine/item/Item.php
> +	 * @param array $lines
this should more accurately be `string[]`, not `array`.

2017-06-22 12:39 UTC, dktapps commented
Your CI build has failed due to the fact you've included an outdated submodule in your changes. Please rebase your branch onto master and fix your submodule versions.

Protip: don't use `git add *` without being 100% certain what's going to get staged.

2017-06-22 22:04 UTC, dktapps commented
You have still included a modified submodule version, please remove the change.

2017-06-23 03:57 UTC, jasonwynn10 commented
git has been fixed! 😄
Finally ready to merge? 😆

2017-06-23 07:39 UTC, dktapps approved these changes

2017-06-23 07:39 UTC, merged