Added API method HelpCommand->setPageSize()
pmmp/PocketMine-MP pull request #1144
Opened 2017-06-27 13:15 UTC by dktapps

## Introduction
Allows plugins to alter the page size for clients shown when using /help.

## Changes
### API changes
- added API method `HelpCommand->setPageSize(int)`

## Tests
tested very quickly, probably ought to check for negative page sizes.

2017-06-27 14:29 UTC, SOF3 commented
This does not conveniently allow setting for different command senders. What about allowing a callable of the prototype `function(CommandSender)`?

2017-06-27 14:30 UTC, SOF3 requested changes
This does not conveniently allow setting for different command senders. What about allowing a callable of the prototype `function(CommandSender) : int`?

Also, making command output pagination an API function that plugins can use is also useful.

2017-07-07 13:25 UTC, dktapps commented
@SOF3 by all means, knock yourself out, but this is a simple change to fix a simple irritation. Console has always used PHP_INT_MAX anyway.

2017-07-08 14:55 UTC, SOF3 approved these changes
Warning: this is a backwards-incompatible API change. If you are sure you don't want to maintain BC by making an extra interface that declares the new method, this PR is OK :+1:

2017-07-13 09:57 UTC, merged