Allow spaces in player's username
pmmp/PocketMine-MP pull request #1152
Opened 2017-06-30 02:46 UTC by mal0ne-23

## Introduction

XBOX Live gamertags support spaces. Without this, it limits gameplay to some players logged into xbox live.

## Changes
### API changes

No API changes.

## Tests

Try to join the server with a username that contains spaces, such as "Name With Spaces" xD

2017-06-30 02:47 UTC, jojoe77777 commented
Good luck with commands.

2017-06-30 02:48 UTC, mal0ne-23 commented
Oh yeah.. That should be done before this is pulled. The command data support..

2017-06-30 08:15 UTC, mal0ne-23 commented
Eventually this will need to be supported, like this isn't a pointless update. Once XBOX Live is enforced, players with gamertags like "monkey man" (god i wish i had that gamertag) wouldn't be able to player on PocketMine servers, due to their username containing spaces.

2017-06-30 08:17 UTC, TheDiamondYT1 commented
Maybe commands with spaces in player names could be done like this:a

In bash, you can can copy multiple directories to a single destination directory in one command, but without quotation marks.
```bash
cp -rf dir1 dir2 dir3 destination
``` 
The above executes correctly. 

Since command arguments are an array, we can use [array_slice()](http://php.net/manual/en/function.array-slice.php) to get the last few arguments of an array. For example:
```php
# Command
/tp player1 player2 x y z

# In the above example, we can shift the last 3 arguments off the array, and use a foreach loop on the players.
```
This could impact on performance, probably, maybe. I dont know.

2017-06-30 08:18 UTC, dktapps commented
XBOX won't be enforced, I don't know why people seem to think it will be. Enforcing XBOX login is the server's decision.

Regardless, MCPE does indeed support names with spaces in them, however PocketMine-MP's command parser does not provide the capability to handle this yet. I'm holding off on command rewrites until 1.2 because a rewrite of commands is coming from Mojang that will be less of a pain in the ass to deal with than the system we have now.

@TheDiamondYT1 just shut up about performance already. It's a damned command. So what? you might lose a couple of nanoseconds? well, that really sucks for those poor nanoseconds, but nobody else is going to care.

2017-06-30 08:24 UTC, mal0ne-23 commented
I don't mean XBOX being enforced on the server. I mean MCPE forcing it. You aren't allowed to logout of XBOX Live on Windows 10. And Xbox One and 360 players are going to be stuck with their gamertag on servers.

Of course the server owner can choose whether or not to check for XBOX live login. That doesn't have to be forced. But, idk.. Not sure if you were talking about the PocketMine server or MCPE enforcing Live in your comment @dktapps, correct me if I'm wrong.

2017-06-30 08:26 UTC, dktapps commented
@mal0ne-23 remind me what version of MCW10 you're using... it stopped forcing XBOX login back at 0.16. But I take your point.

Regardless, this PR isn't about whether to support XBOX players or not, it's whether to allow spaces in usernames. That's a completely independent problem.

2017-06-30 08:38 UTC, mal0ne-23 commented
Ah, nvm it doesn't force XBOX login. But yeah, consoles will most likely force it. Another issue though for another time.

2017-08-02 20:50 UTC, VCraftMCPE commented
@Dktapps in 1.2 update u will be forced to use XBox login to join servers

2017-08-02 20:51 UTC, Driesboy commented
rlly? why??

Op 2-aug.-2017 22:50 schreef "VCraftMCPE" <notifications@github.com>:

> @dktapps <https://github.com/dktapps> in 1.2 update u will be forced to
> use XBox login to join servers
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pmmp/PocketMine-MP/pull/1152#issuecomment-319794369>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/APEEPsYDZT6mT4d-7vtmxzHdVNmVzVG4ks5sUOEagaJpZM4OKFxe>
> .
>

2017-08-02 20:52 UTC, dktapps commented
Yes, we are aware. That's irrelevant to this pull request.

2017-08-03 09:03 UTC, dktapps requested changes
This will also allow players with new-lines and tab characters in their names to join the server. Possibly not expected behaviour.

2017-08-03 09:16 UTC, Muqsit commented
Change the `<= 16` to `<= 15` while you're at it.

![sx](https://user-images.githubusercontent.com/15074389/28914750-7702ba92-785a-11e7-82f3-56f3bf8b1c13.PNG)

2017-08-03 21:54 UTC, mal0ne-23 commented
done

2017-08-04 02:14 UTC, jojoe77777 commented
Now players can't connect with a 16 char name to local servers over LAN

2017-08-04 04:00 UTC, mal0ne-23 commented
Yeah.. Because you can totally do that when xbox live is enforced.

2017-08-04 04:42 UTC, jojoe77777 commented
@mal0ne-23 Xbox live login isn't enforced over LAN

2017-08-04 10:16 UTC, TheDiamondYT1 requested changes

2017-08-04 10:16 UTC, TheDiamondYT1 commented on src/pocketmine/Player.php
> +		return $lname !== "rcon" and $lname !== "console" and $len >= 1 and $len <= 15 and stristr($name, "\n") == false and stristr($name, "\t") == false and preg_match("/[^A-Za-z0-9_\s]/", $name) === 0;
`===` or just `!`

2017-08-20 14:55 UTC, Kenner-G commented
@dktapps 

So as what I understand, Xbox Live will not be enforced in the 1.2 update correct?

2017-08-20 14:58 UTC, Sandertv commented
In 1.2 xbox live accounts will already be enforced.

2017-08-20 15:00 UTC, SuperMaXAleX commented
_facepalm_

2017-09-12 21:20 UTC, closed without merging