Entity Effect Event's
pmmp/PocketMine-MP pull request #141
Opened 2016-12-04 11:00 UTC by JackNoordhuis

Add EntityEffectEvent class that the EntityEffectAddEvent and
EntityEffectRemoveEvent classes extend. Add event calls to Effect class.

This is purely an API addition that allows developers to modify the effect behaviour through the use of plugins.

I have tested this and it works as expected. Some more testing may need to be done to make sure the event's work as expect in all cases.

2016-12-04 11:56 UTC, JackNoordhuis commented
This might be useful to anyone wanting to test out these changes: https://github.com/JackNoordhuis/PocketMine-Plugins/tree/master/EffectEventTesting

2016-12-05 09:32 UTC, dktapps commented on src/pocketmine/entity/Effect.php
> +		($entity, $this, $modify, $oldEffect));
please fix your formatting here.

2016-12-05 10:06 UTC, JackNoordhuis commented on src/pocketmine/entity/Effect.php
> +		($entity, $this, $modify, $oldEffect));
Accidently changed some settings in PHPStorm when I was messing around the other day, fixed.

2016-12-05 10:14 UTC, dktapps approved these changes
Looks good to me, but will let someone else take a look also.

2016-12-05 10:21 UTC, JackNoordhuis commented
Squashed commits just because a derpy formatting fix doesn't deserve its own commit and for convenience.

2016-12-05 11:37 UTC, SOF3 requested changes

2016-12-05 11:37 UTC, SOF3 commented on src/pocketmine/event/entity/EntityEffectAddEvent.php
> +	public function willModify(): bool{
I thought our code style is `willModify() : bool{`

2016-12-05 11:38 UTC, dktapps commented on src/pocketmine/event/entity/EntityEffectAddEvent.php
> +	public function willModify(): bool{
OCD ftw...

2016-12-05 11:39 UTC, dktapps commented on src/pocketmine/event/entity/EntityEffectAddEvent.php
> +	public function hasOldEffect(): bool{
@SOF3 missed one :P

2016-12-05 11:39 UTC, dktapps commented on src/pocketmine/event/entity/EntityEffectEvent.php
> +	public function getEffect(): Effect{
and here ;)

2016-12-05 11:46 UTC, SOF3 commented on src/pocketmine/event/entity/EntityEffectEvent.php
> +	public function getEffect(): Effect{
I don't need to triple comment these, do I ;)

2016-12-05 11:46 UTC, dktapps commented on src/pocketmine/event/entity/EntityEffectEvent.php
> +	public function getEffect(): Effect{
maybe? he won't miss any of them now :O

2016-12-05 11:54 UTC, JackNoordhuis commented on src/pocketmine/event/entity/EntityEffectAddEvent.php
> +	public function willModify(): bool{
Had a feeling it was supposed to be like that, will change.

2016-12-05 12:14 UTC, JackNoordhuis commented
Fixed the return type hint formatting.

2016-12-05 12:47 UTC, SOF3 approved these changes

2016-12-06 11:59 UTC, merged