PluginManager: Altered regex to allow @ignoreCancelled without a value
pmmp/PocketMine-MP pull request #1799
Opened 2017-12-12 11:54 UTC by dktapps

## Introduction
This allows specification of `@ignoreCancelled` on event handlers without a `true` or `false` value. If a value is not specified, `true` is used.

## Changes
### API changes
see intro

## Tests
```php
	/**
	 * @param BlockBreakEvent $event
	 * @ignoreCancelled
         */
	public function onBlockBreak(BlockBreakEvent $event){
		var_dump($event->getPlayer()->lastBreak);
		$event->getPlayer()->sendMessage("Time to break: " . ceil((microtime(true) - $event->getPlayer()->lastBreak) * 20) . " ticks");
		$event->getPlayer()->sendMessage("Expected: " . ceil($event->getBlock()->getBreakTime($event->getItem()) * 20) . " ticks");
	}
```

2017-12-12 11:58 UTC, dktapps commented
OOOpS, this breaks normal specification.

2017-12-12 17:24 UTC, SOF3 commented
I don't know why @shoghicp made it so complicated. It could have been `(bool) preg_match("/^[\t ]*\\* @ignoreCancelled[\t ]{1,}true/m")` in the first place; then this PR can also be as simple as `(bool) preg_match("/^[\t ]*\\* @ignoreCancelled([\t ]{1,}true)?/m")`.

2017-12-13 05:22 UTC, SOF3 requested changes
The code is made unnecessarily confusing. `@ignoreCancelled false` could be directly ignored.

2017-12-31 23:21 UTC, dktapps commented
This was supposed to be a simple change. I separated it from another PR in the hopes of getting it in separately, but since it's more trouble than it's worth, I won't bother.

2017-12-31 23:21 UTC, closed without merging