Added a getEntry() to BanList
pmmp/PocketMine-MP pull request #1830
Opened 2017-12-18 16:05 UTC by zKoz210

## Introduction
Adds direct access to BanEntry

## Changes
### API changes
Added `getEntry(string name): ?BanEntry`

## Backward compatibility
This PR should preserve 100% backward-compatibility

2017-12-20 11:21 UTC, dktapps requested changes
Looks like a reasonable addition, but please see comments on the diff.

2017-12-20 11:21 UTC, dktapps commented on src/pocketmine/permission/BanList.php
> +	public function getEntry(string $name): ?BanEntry{
formatting issue

2017-12-20 11:21 UTC, dktapps commented on src/pocketmine/permission/BanList.php
> +		return $this->list[$name];
the `isset()` and this statement could be merged into a single statement using a null coalesce (`$this->list[$name] ?? null`)

2017-12-20 19:42 UTC, dktapps commented on src/pocketmine/permission/BanList.php
> +		return $this->list[$name] ?? null;
the `strtolower()` can now be moved to here, and remove the first statement, since it's only used once.

2017-12-21 07:54 UTC, SOF3 approved these changes

2017-12-21 10:05 UTC, dktapps approved these changes

2017-12-21 10:05 UTC, dktapps commented
I'd better check the EOF newline before I merge this - not really clear why it still shows up on the diff.

2017-12-21 10:08 UTC, merged