Added Living::getEntityLookingAt() method
pmmp/PocketMine-MP pull request #1984
Opened 2018-01-30 15:57 UTC by xBeastMode

## Introduction
Similar to Living::getTargetBlock() this method is used to get the target entity in the view of a living entity.

### Relevant issues

none.

## Changes
### API changes
Living::getEntityLookingAt() has two (2) optional paremeters:

- **distance**: an AlignedAxisBB class to select the distance in which the function searches, the bigger the distance the farther the function can search. If this parameter is null, the function will search in a 100 block radius.
- **precision**: a float that indicates how precise the entity has to be poiting to get the exact target entity. Values >= `0.998` indicate that the entity should be looking exactly at another entity, never use a value >= `1.0`

### Behavioural changes
none.

## Backwards compatibility
none.

## Follow-up
none.

## Requires translations:

none.

## Tests
```Living::getEntityLookingAt()``` was tested by swapping positions with the target entity when the client right clicked. The client was not teleported when not looking directly at an entity.

2018-01-31 11:03 UTC, dktapps requested changes

2018-01-31 11:03 UTC, dktapps commented on src/pocketmine/entity/Living.php
> +                        $pointB = $this->add(100, 100, 100);
??????? Why on earth ???????

It should be more than sufficient to give a floating-point linear distance, and then multiply the entity's direction vector by it to obtain points A and B:

```php
$pointA = $this->asVector3();
$pointB = $this->getDirectionVector()->multiply($linearMaxDistance);
```

This solution is ludicrously inefficient.

2018-01-31 11:03 UTC, dktapps commented on src/pocketmine/entity/Living.php
> +                        $exact = $toEntity->normalize()->dot($direction);
This shouldn't be necessary. Getting the entity's AABB and checking for an intercept between the points should be sufficient.

2018-01-31 11:03 UTC, dktapps commented on src/pocketmine/entity/Living.php
> +                        if($entity === $this) continue;
The second parameter of `getNearbyEntities()` should be used for this.

2018-01-31 11:03 UTC, dktapps commented on src/pocketmine/entity/Living.php
> +                        $distance = new AxisAlignedBB($pointA->x, $pointA->y, $pointA->z, $pointB->x, $pointB->y, $pointB->z);
Following from my above comment, the first three parameters should be the lesser of each x,y,z and the second three should be the greater ones.

2018-01-31 11:03 UTC, dktapps commented on src/pocketmine/entity/Living.php
> +                                return $entity;
No distance checking? You want the entity closest to this entity along its line of sight.

2018-01-31 11:03 UTC, dktapps commented on src/pocketmine/entity/Living.php
> +         *
redundant empty line

2018-01-31 11:03 UTC, dktapps commented on src/pocketmine/entity/Living.php
> +        public function getEntityLookingAt(AxisAlignedBB $distance = null, float $precision = 0.998){
a `?Entity` typehint can be applied here.

2018-01-31 11:03 UTC, dktapps commented on src/pocketmine/entity/Living.php
> -
unrelated formatting change

2018-01-31 11:03 UTC, dktapps commented on src/pocketmine/entity/Living.php
> +                        if($exact >= $precision){
This is unnecessary if an AABB ray trace is used.

2018-02-05 12:46 UTC, Doreez commented
Definitely

2018-02-06 21:28 UTC, dktapps commented
Has been discussed with author elsewhere, who doesn't want to continue with it.

2018-02-06 21:28 UTC, closed without merging