Add 0.16 blocks/items
pmmp/PocketMine-MP pull request #210
Opened 2016-12-28 22:45 UTC by AppleDevelops

This PR adds all (most if I'm wrong) of 0.16 blocks and items.

2016-12-28 22:58 UTC, dktapps requested changes
BTW the reason we haven't added these ourselves is because we are currently planning rewrites.

Please attend to my comments on the diff.

2016-12-28 22:58 UTC, dktapps commented on src/pocketmine/resources/creativeitems.json
> +	{
This file is auto-generated, don't modify it by hand. It should already be up-to-date for 0.16.

2016-12-28 22:58 UTC, dktapps commented on src/pocketmine/item/ItemIds.php
> -	const MINECART_WITH_HOPPER = 408, HOPPER = 410;
lol @SOF3 , blame your automated formatting ;P

2016-12-28 22:58 UTC, dktapps commented on src/pocketmine/block/Beacon.php
> + 		$pot = Tile::createTile(Tile::BEACON, $this->getLevel()->getChunk($this->x >> 4, $this->z >> 4), $nbt);
careful with the copy-paste ;)

2016-12-28 22:58 UTC, dktapps commented on src/pocketmine/block/Prismarine.php
> +	public function getName() : string{
iirc the base method doesn't have type-hint, you might want to remove this.

2016-12-28 22:58 UTC, dktapps commented on src/pocketmine/block/Prismarine.php
> +	public function getDrops(Item $item) : array {
same here

2016-12-28 22:58 UTC, dktapps commented on src/pocketmine/block/SeaLantern.php
> +	public function getName() : string{
and here.. I think you get the idea

2016-12-28 23:03 UTC, AppleDevelops commented
I'll work on it when I get back. It's copy and pasted from my dead software which used a lot of spaces. (Everyone used GitHub web editor for some reason)

2016-12-28 23:19 UTC, dktapps commented on src/pocketmine/tile/Beacon.php
> + 	public function __construct(Chunk $chunk, CompoundTag $nbt){
You're PRing to master, which doesn't have 1.0 changes yet. This should more correctly be FullChunk on the current master.

2016-12-28 23:50 UTC, AppleDevelops commented on src/pocketmine/tile/Beacon.php
> + 	public function __construct(Chunk $chunk, CompoundTag $nbt){
@dktapps My bad 😄

2016-12-29 02:14 UTC, AppleDevelops commented
There you go :)

2016-12-29 11:34 UTC, dktapps approved these changes

2016-12-29 11:35 UTC, merged

2022-08-12 21:49 UTC, sylvrs commented
finally, 0.16 support