Player Entity Interaction
pmmp/PocketMine-MP pull request #2352
Opened 2018-08-03 10:05 UTC by Spajker7

## Introduction
This PR implements Player -> Entity interaction ( right clicking entities ).

### Relevant issues
/

## Changes
### API changes
Added Entity::onPlayerInteract method
Added Item::onClickEntity method
Added PlayerInteractEntityEvent event

### Behavioural changes
/

## Backwards compatibility
Changes are additions, so they are backwards compatible 

## Follow-up
/

## Tests
/

2018-08-03 20:13 UTC, Enes5519 requested changes

2018-08-03 20:13 UTC, Enes5519 commented on src/pocketmine/entity/Entity.php
> +	public function onPlayerInteract(Player $player, Item $heldItem, Vector3 $clickPos) : bool {
I think change the function's name to ``onInteract`` and You must change ``: bool {`` to ``: bool{``

2018-08-03 20:13 UTC, Enes5519 commented on src/pocketmine/event/player/PlayerInteractEntityEvent.php
> +{
remove eol

2018-08-05 21:49 UTC, Spajker7 commented
I am closing the PR since Dylan mentioned he'll implement this himself.

2018-08-05 21:49 UTC, closed without merging