Removed useless strtolower calls
pmmp/PocketMine-MP pull request #2371
Opened 2018-08-12 18:24 UTC by Frago9876543210

## Introduction
This PR removes useless strtolower calls, because it is will called earlier.
https://github.com/pmmp/PocketMine-MP/blob/078a2486b5e56fb2e9b4f709d566b255872b80db/src/pocketmine/Server.php#L728-L737

2018-08-12 18:31 UTC, dktapps requested changes
Looks OK apart from one nitpick.

2018-08-12 18:31 UTC, dktapps commented on src/pocketmine/OfflinePlayer.php
> +		if(file_exists($this->server->getDataPath() . "players/" . $this->name . ".dat")){
It's possible that an `OfflinePlayer` instance may be constructed by something else (such as a unit test), in which case the name might not be passed in lowercase. The class should not rely on the caller to do its work for it. At the least this check should be `strtolower()`d.

2018-08-12 18:35 UTC, dktapps commented on src/pocketmine/OfflinePlayer.php
> +		$this->name = strtolower($name);
I was talking about the `file_exists()` check. The case of the passed name should be preserved on the property.

2018-08-12 19:33 UTC, jasonw4331 requested changes
Here's my nitpick

2018-08-12 19:33 UTC, jasonwynn10 commented on src/pocketmine/OfflinePlayer.php
> +		$this->iusername = strtolower($this->name);
use `$name` here instead of `$this->name`

2018-08-13 02:30 UTC, jasonw4331 approved these changes

2018-08-13 11:48 UTC, lukeeey commented
i thought i already fixed this in my PR?

2018-08-13 12:09 UTC, Frago9876543210 commented
BTW, the problem is not just strtolower calls. Look at the that code:
```php
public function getMoney(IPlayer $player) : int{
	return (int) $this->money->get(strtolower($player->getName()), self::DEFAULT_MONEY);
}
```
Sometimes, it is quite convenient to use IPlayer as argument. However, if the IPlayer will be OfflinePlayer it return name in lower case, but if the player is online, then his name in will be returned without lower case. This PR fixes this. And adds to the interface `getLowerCaseName()`

2018-08-13 12:23 UTC, closed without merging