Allow plugins to disable background generation
pmmp/PocketMine-MP pull request #2613
Opened 2018-12-27 14:23 UTC by Frago9876543210

## Introduction
See title

## Changes
### API changes
```diff
- Server::generateLevel(string $name, int $seed = null, $generator = null, array $options = [])
+ Server::generateLevel(string $name, int $seed = null, $generator = null, array $options = [], bool $backgroundGeneration = true)
```

2018-12-27 17:20 UTC, dktapps requested changes
Looks fine after nits are fixed.

2018-12-27 17:20 UTC, dktapps commented on src/pocketmine/Server.php
> +	public function generateLevel(string $name, int $seed = null, $generator = null, array $options = [], $backgroundGeneration = true) : bool{
```suggestion
	public function generateLevel(string $name, int $seed = null, $generator = null, array $options = [], bool $backgroundGeneration = true) : bool{
```

2018-12-27 17:23 UTC, dktapps approved these changes

2018-12-28 10:06 UTC, dktapps commented
This might have unintended side effects on world loading. If no spawn chunks are generated, the initial region on Region-based worlds will not be created, which will prevent the format selector detecting the correct world format. Plugins would have to set chunks into the world before unloading it, or risk the empty world getting overwritten with a new one.

2018-12-28 13:34 UTC, Frago9876543210 commented
Yes, it has side effects, but the responsibility lies with the plugins. This can simplify the format conversion, which is required later.

2018-12-28 14:34 UTC, merged