Added notifications manager
pmmp/PocketMine-MP pull request #2648
Opened 2019-01-06 11:41 UTC by SOF3

## Introduction
Some warning messages can be dismissed after the user has read the messages. This pull request adds a manager for dismissed messages, and implements this for the "auth enabled" message.

### Relevant issues

## Changes
### API changes
Added Server->getNotificationManager()

### Behavioural changes
- Added a /notif command.
- The "auth enabled/disabled" notice/warning message is no longer displayed if the user runs `notif read` from console anytime.

## Backwards compatibility
No backward compatibility problems

## Follow-up

Requires translations:

| Name | Value in eng.ini |
| :--: | :---: |
| `pocketmine.command.notif.description` | `View and manage notifications` |
| `pocketmine.command.notif.usage` | `/notif [list|read]` |
| `pocketmine.notification.markedRead` | `Marked {%0} notifications as read.` |
| `pocketmine.notification.header` | `There are {%0} unread notifications` |
| `pocketmine.command.notif.description` | `Run "/notif read" to not show these notifications again.` |

## Tests

### Prints unread messages upon startup
Start the default server setup. The startup screen should end with this:
```
[19:29:25] [Server thread/NOTICE]: pocketmine.notification.header
[19:29:25] [Server thread/NOTICE]: Online mode is enabled. The server will verify that players are authenticated to Xbox Live.
[19:29:25] [Server thread/NOTICE]: To disable authentication, set "xbox-auth" to "false" in server.properties.
[19:29:25] [Server thread/NOTICE]: pocketmine.notification.footer
[19:29:25] [Server thread/INFO]: Done (0.884s)! For help, type "help" or "?"
```

### Prints unread messages upon command
Start the default server setup. Run `notif` or `notif list`. The following output is expected:
```
[19:29:28] [Server thread/NOTICE]: pocketmine.notification.header
[19:29:28] [Server thread/NOTICE]: Online mode is enabled. The server will verify that players are authenticated to Xbox Live.
[19:29:28] [Server thread/NOTICE]: To disable authentication, set "xbox-auth" to "false" in server.properties.
[19:29:28] [Server thread/NOTICE]: pocketmine.notification.footer
```

### Mark notifications as read
Start the default server. Run `notif read`. The following output is expected:
```
[19:29:29] [Server thread/INFO]: %pocketmine.notification.markedRead
```

Then restart the server. The "online mode" notice should no longer be displayed. Nor should `pocketmine.notification.[header|footer]` be displayed.

2019-01-06 19:44 UTC, Frago9876543210 commented
Wow, looks cool! How about show count notifications in screen title?

2019-03-10 13:48 UTC, lukeeey commented
Why

2019-03-10 16:21 UTC, SOF3 commented
Some messages are important warnings, but they become annoying after the user reads them the first time. They are particularly distracting if they are in aqua/yellow, which is reasonable because they are important warnings.

2019-08-20 18:49 UTC, omerien commented
I can translate in french

2023-08-28 13:59 UTC, ShockedPlot7560 reviewed
I find this PR correct. Despite a rejuvenation of the code to add typing to properties etc, in my opinion it could be merge. 

Is there a reason why it hasn't been merged?

2023-08-28 15:13 UTC, jasonw4331 requested changes
Just my nitpick which would be irrelevant if command names get removed

2023-08-28 15:13 UTC, jasonw4331 commented on src/pocketmine/command/SimpleCommandMap.php
> +			new NotificationsCommand("notif"),
The command name should be the full word by default and "notif" should be an alias in my opinion.

2023-08-28 15:13 UTC, jasonw4331 commented on src/pocketmine/command/defaults/NotificationsCommand.php
> +			["notification", "notifications", "notifs"]);
same as previous comment.

2023-08-29 02:16 UTC, SOF3 commented
tbh I think this feature is pretty pointless since nobody wants to manage the startup logs after all. If anyone intends to fix this, we should look into a better frontend instead, e.g. #3046 
I'm closing this PR for now, but in case anyone wants to pick this up, feel free to reopen.

2023-08-29 02:16 UTC, closed without merging