Allow gamemode string in server.properties
pmmp/PocketMine-MP pull request #2752
Opened 2019-02-10 17:42 UTC by JackNoordhuis

Addresses #2692.

2019-02-10 17:44 UTC, dktapps commented
There is no error checking in this PR, which will cause the server to crash if an invalid gamemode is found in server.properties. This is why I did not apply this change myself, as trivial as it looks.

2019-02-10 17:46 UTC, JackNoordhuis commented
I wasn't sure what behaviour to implement for catching the error. I don't think the server should start given a bad configuration but a warning and defaulting back to survival could be an alternative?

2019-02-10 17:47 UTC, dktapps commented
The configuration crashing issue is a more general problem. The point is that I explicitly avoided applying this change myself because of the additional problems it would cause without a proper solution for config handling.

2019-03-18 09:34 UTC, dktapps requested changes

2019-03-18 09:34 UTC, dktapps commented on src/pocketmine/Server.php
> +		return GameMode::fromString($this->getConfigString("gamemode", "s"));
I would be happier if `(string) GameMode::SURVIVAL` was used here. It's too easy to miss this if refactors happen.

2019-03-18 09:34 UTC, dktapps commented on src/pocketmine/Server.php
> +		return GameMode::fromString($this->getConfigString("gamemode", "s"));
and here too (ofc)

2019-10-04 08:46 UTC, dktapps commented
Closing due to lack of activity on review comments.

2019-10-04 08:46 UTC, closed without merging