Add API methods to change a players' player list name
pmmp/PocketMine-MP pull request #2977
Opened 2019-06-21 13:29 UTC by lukeeey

## Introduction
Since the ability to update the player list was removed when calling `setDisplayName` (and rightly so), we need another method update the name. 

## Changes
### API changes
Add the following methods to Player:
* `getPlayerListName()`
* `setPlayerListName(string $name)`

## Backwards compatibility
It is but does it even really matter at this point? lol

## Follow-up
Maybe use the player list name instead of the username in `NetworkSession->onPlayerAdded()` as the plain username will be displayed until the player actually spawns (if you use my join event example, i'm not sure if it would be possible to change the name in an earlier event)

## Tests
```php
public function onJoin(PlayerJoinEvent $event): void {
        $player = $event->getPlayer();
        $player->setPlayerListName(TF::LIGHT_PURPLE . "[PLN] " . $player->getName());
    }
```

2019-06-21 13:32 UTC, ErkamKahriman commented
i like that

2019-06-21 13:32 UTC, lukeeey commented
Hmm what about removing the entry and then adding it again like frago did

2019-06-21 14:08 UTC, lukeeey commented
Sorry about formatting but im about to go out i can fix later if needed and ive allowed edits from maintainers

2019-06-21 14:10 UTC, Frago9876543210 requested changes
onPlayerAdded also should use getPlayerListName()

2019-06-21 14:28 UTC, Wertzui123 commented
What do you mean with listname?

2019-06-21 15:03 UTC, lukeeey commented
@Frago9876543210 Dylan wasnt sure about that which is why i added it in the follow up

2019-07-19 10:06 UTC, Frago9876543210 commented
@dktapps because getDisplayName used for chat what can cause conflict

2019-07-19 10:08 UTC, dktapps commented
That doesn't answer my question. Display name was used for player list for years without any complaints.

2019-07-19 10:19 UTC, ErkamKahriman commented
But if you setDisplayName then the name in playerlist will be like §4Owner §8» §f123456789123456789
and no one can ready that

2019-07-19 10:21 UTC, dktapps commented
Player list is an insignificant part of gameplay. The time you spend looking at it is minimal. It could use standard username and nobody would notice.

2019-07-19 11:06 UTC, lukeeey commented
Well an alternative reason for this is for either third party clients like alex that implement a tablist or if it gets implemented into the client itself.

Also a players display name may be something quite long, like
```
§b[Owner] §cAQuiteLongUsername
```
This means most of the players actual username may be cut out of the player list entry. 

I may want to just set the players player list name to the players name as the colour red so people can see i have the owner rank but without the rank name in there taking up space.


Also ive just thought that when implementing a nickname system, you generally setthe players display name. This would change it in the player list too, which may not he expected behaviour.

2019-07-19 11:07 UTC, lukeeey commented
And while yes its insignificant, that doesnt mean we shouldnt give users the choice to change it

2019-12-15 09:15 UTC, SOF3 approved these changes

2019-12-15 09:19 UTC, SOF3 commented
> Player list is an insignificant part of gameplay. The time you spend looking at it is minimal. It could use standard username and nobody would notice.

I don't think this is a valid reason to reject this pull request. If there is nothing wrong, why can't we get it merged? If someone created this pull request, it's here for some reason.

The only issue I see with this pull request is that `getDisplayName` now has an ambiguous meaning, and that `setDisplayName()` now doesn't change the player list value. This is indeed an unresolved question and a BC break, but I don't see this mentioned above.

Suggestion: Reorient this pull request into "split display name into chat name and player list name", and deprecate/remove `getDisplayName` and `setDisplayName`.

2019-12-15 10:14 UTC, dktapps commented
> If there is nothing wrong, why can't we get it merged? 

because it adds extra complexity for a fringe feature that doesn't matter 99.9% of the time anyway.

2023-03-07 17:26 UTC, closed without merging