MetadataProperties: id, data => static runtime id
pmmp/PocketMine-MP pull request #3007
Opened 2019-07-11 17:20 UTC by Frago9876543210

2019-07-12 09:34 UTC, Enes5519 approved these changes

2019-07-12 09:43 UTC, dktapps requested changes

2019-07-12 09:43 UTC, dktapps commented on src/pocketmine/network/mcpe/protocol/types/EntityMetadataProperties.php
>  	public const HORSE_FLAGS = 16; //int
this is not a static ID

2019-07-19 09:31 UTC, dktapps commented
I don't want to merge this on master because it's going to get overwritten the next time I have to integrate changes from stable. You should make your change there instead.

2019-07-19 09:31 UTC, closed without merging