Add comment to make what duration is in more obvious
pmmp/PocketMine-MP pull request #3256
Opened 2019-12-22 17:51 UTC by Zedstar16

## Introduction

### Relevant issues

## Changes
### API changes

### Behavioural changes

## Backwards compatibility

## Follow-up

## Tests

2019-12-22 18:00 UTC, dktapps reviewed
looks OK, but pls use tabs for indentation instead of spaces

2019-12-23 12:28 UTC, SOF3 requested changes

2019-12-23 12:28 UTC, SOF3 commented on src/pocketmine/entity/EffectInstance.php
> +     *
and the second line too...

2019-12-24 22:22 UTC, dktapps commented on src/pocketmine/entity/EffectInstance.php
> +     *
why is this marked as resolved?

2019-12-29 18:59 UTC, dktapps commented
Closing this due to too much hassle for such a small change; it can be applied by a maintainer without waiting for review comments to be addressed.

2019-12-29 18:59 UTC, closed without merging