Remove parameter $isAdmin from Player::kick()
pmmp/PocketMine-MP pull request #3275
Opened 2020-01-15 07:27 UTC by Muqsit

## Introduction

The `$isAdmin` parameter in `Player->kick()` servers not much of a purpose besides further modifying the `$reason` parameter. As by default, the parameter is `true` this could result in a misleading kick message.

Plugins may want to kick players for various other reasons which do not require an admin intervention (eg: anticheat and anti-afk plugins) but the `$isAdmin` parameter is dedicated to serve only the purposes that were resulted by an admin kicking, among the several other purposes.
So the "Kicked by admin." prefix is better handled by the method caller than the method itself.

At the moment, `Player->kick()` is called in 5 places:
```php
BanCommand.php:61:           $player->kick($reason !== "" ? "Banned by admin. Reason: " . $reason : "Banned by admin.");
BanIpCommand.php:84:         $player->kick($reason !== "" ? $reason : "IP banned.");
KickCommand.php:61:          $player->kick($reason);
Player.php:390:              $this->kick("You have been banned");
Player.php:1774:             $this->kick("Attempting to attack an invalid entity");
```
1. The first one, in BanCommand serves no purpose as there's already a "Banned by admin." prefix before the ban reason.
2. The second usage is arguable. Adding a "Banned by admin." over there might be helpful assuming the majority users set a vague ban reason. For example: `/ban-ip player flying` would send the player a disconnect screen with only `flying` displayed. (RFC?)
3. Same as point 2, assuming the majority users `/kick player flying`.
4. Arguable since a ban is most likely the result of an admin intervention. This could be misleading when the server is set to hardcore mode where a player isn't banned as a result of admin intervention.
5. Results in a misleading kick screen as player isn't kicked by an administrator.

## Changes
### API changes

Removes optional parameter `$isAdmin` from `Player::kick()`.

### Behavioural changes

The server no longer adds the `Kicked by admin.` prefix to kick and ban messages.

## Backwards compatibility

Breaks plugins that supplied more than 1 parameter to `Player::kick()`.
Plugins that would like to maintain the previous behaviour may migrate as follows:

| Before | After |
| --- | --- |
| `$player->kick($reason, false);` | `$player->kick($reason);` |
| `$player->kick($reason, false, $quitMessage);` | `$player->kick($reason, $quitMessage);` |
| `$player->kick($reason, true);` | `$player->kick("Kicked by admin." . ($reason !== "" ? " Reason: " . $reason : ""));` |
| `$player->kick($reason, true, $quitMessage);` | `$player->kick("Kicked by admin." . ($reason !== "" ? " Reason: " . $reason : ""), $quitMessage);` |

## Follow-up
Updating changelog

## Tests

Script plugin that kicks a player without adding the "Kicked by admin." prefix: https://gist.github.com/Muqsit/645e1e54fc9593416d7fcb5bed29d792

2020-01-15 07:34 UTC, SOF3 approved these changes
I would prefer merging this after we have consensus on what to do with the `TextContainer|string|null` mess.

2020-01-15 10:21 UTC, dktapps commented
I think the `/kick` command should add the `Kicked by admin` prefix explicitly, similar to how `/ban` does it.

2020-01-15 10:56 UTC, Muqsit commented
The same goes for BanIpCommand too, right?

2020-01-15 10:57 UTC, dktapps commented
disconnect messages should be making sense regardless of API changes

2020-02-10 10:34 UTC, dktapps commented
this is now problematic to merge because there are needed changes, but you've deleted the downstream repository.

2020-02-10 10:38 UTC, dktapps requested changes
These lines should also be updated: https://github.com/pmmp/PocketMine-MP/pull/3275/files#diff-6e3ab584fcfae48a1f070adc1de82abdR2080-R2081

2020-02-10 10:38 UTC, dktapps commented on src/command/defaults/BanIpCommand.php
> +				$player->kick($reason !== "" ? "IP banned by admin. Reason: " . $reason : "IP banned by admin.");
For some reason I'm not able to provide suggested changes, but the following would be better:
```php
$player->kick("IP banned by admin." . ($reason !== "" ? " Reason: " . $reason : ""));
```

2020-02-10 10:38 UTC, dktapps commented on src/command/defaults/KickCommand.php
> +			$player->kick($reason !== "" ? "Kicked by admin. Reason: " . $reason : "");
```php
$player->kick("Kicked by admin." . ($reason !== "" ? " Reason: " . $reason : ""));
```

2020-02-10 10:40 UTC, dktapps commented
> I would prefer merging this after we have consensus on what to do with the TextContainer|string|null mess.

My current plan is to make `TranslationContainer|null` the accepted type, and box raw strings inside a special `raw` translation key. `TextContainer` has been scrapped because it doesn't make any sense (see 4c51f1dda348d9d1c53c89185ceeb909a1cad21a).

2020-02-13 09:57 UTC, lukeeey commented
Also rename it to `Translation`

2020-05-03 21:50 UTC, dktapps commented
Implemented in 5a33dbd4c6a88e86c2b0b2f4365429e615c26d3a.

2020-05-03 21:50 UTC, closed without merging