Knockback edit
pmmp/PocketMine-MP pull request #3782
Opened 2020-08-20 09:51 UTC by jkorn2324

## Introduction

This pull request adds more flexibility to developers trying to add completely customizable knockback. Instead of a base knockback value that controls both the horizontal knockback (how far the entity goes after each hit) and the vertical knockback (how high the entity goes after each hit), this pull request separates the base horizontal and base vertical knockback values so allow for more customization without needing to create a Player class as shown in my plugin: https://github.com/jkorn2324/PvPCore. 

### Relevant issues

No issues so far.

## Changes
### API changes

**Added Methods:**
EntityDamageByEntityEvent->getHorizontalKnockback();
EntityDamageByEntityEvent->getVerticalKnockback();
EntityDamageByEntityEvent->setHorizontalKnockback();
EntityDamageByEntityEvent->setVerticalKnockback();

**Changed Methods:**
EntityDamageByEntityEvent->setKnockBack();
EntityDamageByEntityEvent->getKnockBack();
Living->knockBack();

### Behavioural changes

No Behavioural changes, just API changes.

## Backwards compatibility

This is backwards-compatible with the current API.

## Follow-up

Determine whether the function names in EntityDamageByEntityEvent are clear enough and whether or not I even need the setVerticalKnockback/setHorizontalKnockback functions if the function names are confusing.

## Tests

Tested by changing the Horizontal Knockback, Vertical Knockback in a plugin using this updated API and by going on a test server and having two players hit each other.

API Tests Video Link:
https://www.dropbox.com/s/ls0kqq04bke17jk/API%20Tests.MOV?dl=0

2020-08-20 10:28 UTC, dktapps requested changes
The formatting in this PR is a mess.

This is also an alarmingly large amount of changes for what's essentially just allowing to customise the vertical knockback limit.

2020-08-20 21:49 UTC, jkorn2324 commented
What do you mean by formatting in this context? Do you have any specific critiques to make it more organized?

2020-08-20 22:22 UTC, dktapps commented
![image](https://user-images.githubusercontent.com/14214667/90831523-d5564d80-e33b-11ea-98f5-e6b8c46e6326.png)
![image](https://user-images.githubusercontent.com/14214667/90831531-da1b0180-e33b-11ea-838b-d87e91e9623f.png)
![image](https://user-images.githubusercontent.com/14214667/90831544-e1daa600-e33b-11ea-9c6c-795ae7a7c645.png)

There's a bunch of other minor spacing issues, but the indentation here is awful.

2020-08-20 23:02 UTC, jasonw4331 requested changes
Please fix the formatting

2020-08-20 23:02 UTC, jasonwynn10 commented on src/pocketmine/entity/Living.php
> +	    $f = sqrt($x * $x + $z * $z);
tabs vs spaces

2020-08-20 23:02 UTC, jasonwynn10 commented on src/pocketmine/entity/Living.php
> +
new lines inserted

2020-08-20 23:02 UTC, jasonwynn10 commented on src/pocketmine/event/entity/EntityDamageByEntityEvent.php
> +            $this->verticalKnockBack = $this->horizontalKnockBack;
tabs vs spaces

2020-08-20 23:02 UTC, jasonwynn10 commented on src/pocketmine/event/entity/EntityDamageByEntityEvent.php
> +
random new line

2020-08-20 23:02 UTC, jasonwynn10 commented on src/pocketmine/entity/Living.php
> +
random new line

2020-08-20 23:26 UTC, jkorn2324 commented on src/pocketmine/entity/Living.php
> +
> Please fix the formatting

Added your suggestions

2020-08-21 02:15 UTC, jasonwynn10 commented on src/pocketmine/entity/Living.php
> +		if ($source instanceof EntityDamageByEntityEvent and
also some tabs were changed to spaces

2020-10-07 19:16 UTC, CortexPE commented
This could be done by plugins, like I've done myself without changing `Player` class more than two years ago.
Gotta admit that it is very hacky but it's possible without all these extra code. Doesn't even use reflection...
Not sure if I could disclose the details on how I did it even without modifying PM itself but it is indeed possible.

In my method, you'd just really have to reimplement the knockback logic yourself... which on the plus side, does give you full customizability on it

2021-03-22 13:36 UTC, dktapps commented
This is stale, overcomplicated, and breaks backwards compatibility.

In a nutshell, what's needed here is a way to limit the maximum vertical knockback. Currently, vertical knockback limit scales with the knockback force, which is not supposed to be the case (as in vanilla). Implementing this should be much simpler than the changes seen in this PR, minus the fact that adding an extra parameter to Living->knockBack() would also break BC.

Considering the age of this problem and the ramifications for BC, I think a solution is better targeted at PM4.

2021-03-22 13:36 UTC, closed without merging