Improving the language system
pmmp/PocketMine-MP pull request #3998
Opened 2021-01-08 19:32 UTC by Saehing

Introduction
This PR contributes to improving the server language system, also correcting some inconsistencies.

Relevant issues
Fixed translation of the text for the player is used. Previously, a player took as a basis the language that is selected on the server, now for each player his language pack is automatically selected, based on his language from LoginPacket.
Introduction
This PR helps improve the server's language system, as well as correcting some inconsistencies.

Related issues
Fixed text translation is used for the player. If previously the player used the language selected on the server as the basis, now each player automatically selects their language pack based on their language from LoginPacket.
API changes
Using the function "loadLanguages()" in LanguageManager you can now load your language packs, this can be used in plugins.

Backward compatibility
This PR is compatible with old plugins.

2021-01-08 20:42 UTC, jasonwynn10 requested changes
Code Formatting needs fixed and BC Breaks need to be labeled before completion

2021-01-08 20:42 UTC, jasonwynn10 commented on src/Server.php
> +    private $languageManager;
Code formatting

2021-01-08 20:42 UTC, jasonwynn10 commented on src/lang/Language.php
> -	public function __construct(string $lang, ?string $path = null, string $fallback = self::FALLBACK_LANGUAGE){
Changing constructor value types is BC breaking

2021-01-08 20:42 UTC, jasonwynn10 commented on src/player/Player.php
> +    protected $language;
Code formatting

2021-01-08 20:42 UTC, jasonwynn10 commented on src/player/Player.php
> +        $this->language = $server->getLanguageManager()->get(LanguageCodeMapping::get($playerInfo->getLocale()));
Seriously, code formatting

2021-01-08 20:42 UTC, jasonwynn10 commented on src/wizard/SetupWizard.php
> +        $this->lang = new Language($lang, LanguageManager::loadLang(RESOURCE_PATH . 'locale/', $lang), new Language(LanguageManager::FALLBACK_LANGUAGE, LanguageManager::loadLang(RESOURCE_PATH . 'loca
Is it too hard to keep the code formatting consistent with the project your editing?

2021-01-08 23:28 UTC, jasonwynn10 requested changes
Many tabs have been turned into spaces... Please fix your IDE settings

2021-01-08 23:28 UTC, jasonwynn10 commented on src/Server.php
> +            $this->languageManager = new LanguageManager(RESOURCE_PATH . 'locale/');
This section is formatted with spaces instead of tabs

2021-01-08 23:28 UTC, jasonwynn10 commented on src/lang/Language.php
> +    /** @var string */
This section is formatted with spaces instead of tabs

2021-01-08 23:28 UTC, jasonwynn10 commented on src/lang/Language.php
> +    /**
This section is formatted with spaces instead of tabs

2021-01-08 23:28 UTC, jasonwynn10 commented on src/lang/Language.php
> +    protected function fallbackInternalGet(string $id) : ?string{
This section is formatted with spaces instead of tabs

2021-01-08 23:28 UTC, jasonwynn10 commented on src/lang/LanguageManager.php
> +<?php
This entire file is formatted with spaces instead of tabs

2021-01-08 23:28 UTC, jasonwynn10 commented on src/network/mcpe/protocol/types/LanguageCodeMapping.php
> +<?php
This entire file is formatted with spaces instead of tabs

2021-01-08 23:28 UTC, jasonwynn10 commented on src/wizard/SetupWizard.php
> +        $this->lang = new Language($lang, RESOURCE_PATH . 'locale/');
spaces here should be tabs

2021-01-09 21:38 UTC, Saehing commented
@jasonwynn10, I think I've fixed it

2021-01-09 23:04 UTC, jasonwynn10 requested changes
A few more missed tid bits

2021-01-09 23:04 UTC, jasonwynn10 commented on src/lang/Language.php
> +        return $this->langValues[$id] ?? null;
this function is formatted with spaces instead of tabs

2021-01-09 23:04 UTC, jasonwynn10 commented on src/player/Player.php
> +            if (($language = $server->getLanguageManager()->get($languageCode)) !== null) {
this if statement is formatted with spaces instead of tabs

2021-02-19 11:36 UTC, Saehing commented
I would make a fallback instead of a static fallback, a fallback in the Language constructor. This should not affect the " BC break”

2021-03-31 19:12 UTC, Saehing commented
Do I need to perform any actions? Or this topic is not relevant at the moment

2021-04-01 00:03 UTC, SOF3 commented
Your PR description is still very unclear. It is impossible to review a large pr without having a clear summary that explains what you are trying to do.

I recommend that you create an RFC at https://github.com/pmmp/PocketMine-MP/discussions to clarify your ideas

2021-07-22 13:32 UTC, dktapps commented
I'm going to close this because the PR is too noisy - it's trying to do multiple different things at the same time and I'm having a hard time separating them. If you want to contribute in the future, you should stick to doing one thing at a time per PR.

2021-07-22 13:32 UTC, closed without merging