Pre-sort items for better inventory distribution
pmmp/PocketMine-MP pull request #4237
Opened 2021-06-03 22:16 UTC by jasonwynn10

## Introduction

Dylan posted an issue on it, so its getting changed.

### Relevant issues

Fixes #1412

## Changes
### API changes

`InventoryHelpersTrait::addItem()` will now stack items together even when provided separately as parameters.

### Behavioral changes

N/A

## Backwards compatibility

N/A

## Follow-up

N/A

## Tests

```php
$inventory->addItem(
	VanillaBlocks::OAK_PLANKS()->asItem()->setCount(16),
	VanillaBlocks::OAK_PLANKS()->asItem()->setCount(16),
	VanillaBlocks::OAK_PLANKS()->asItem()->setCount(16),
	VanillaBlocks::OAK_PLANKS()->asItem()->setCount(16)
);
```

![image](https://user-images.githubusercontent.com/16521025/120718746-c8a08180-c497-11eb-8e16-4dd30db1e54d.png)

2021-06-03 23:04 UTC, dktapps commented
To be honest, I think a better solution is to just separate the logic of addItem() into an internal method, and then call the internal method once for each argument. That would guarantee consistency with minimal changes.

2021-06-04 00:08 UTC, jasonwynn10 commented
Is that closer to what you're talking about?

2021-06-04 08:35 UTC, dktapps commented on src/inventory/InventoryHelpersTrait.php
>  				//This loop only gets the first item, then goes to the next empty slot
The loop that this comment describes no longer exists.

2021-06-09 12:59 UTC, dktapps commented
Please write a PHPUnit test for this.

2021-06-17 14:40 UTC, dktapps requested changes
This PR should include unit tests to show that the behaviour is as expected (the behaviour of addItem(1, 2, 3, 4) should be the same as 4 separate addItem() calls).

2021-06-17 14:40 UTC, dktapps commented on src/inventory/InventoryHelpersTrait.php
> +			$returnSlots[] = $this->internalAddItem($item);
This should check if the returned item `isNull()`, and don't add it to the result if so.

2021-06-17 20:04 UTC, dktapps approved these changes

2021-06-17 20:05 UTC, merged