Transferserver
pmmp/PocketMine-MP pull request #4266
Opened 2021-06-13 14:57 UTC by ShockedPlot7560

## Introduction

The /transferserver command could only be used by the person himself, and not transferred to any player.
### Relevant issues

Fixes: pmmp/PocketMine-MP#4065

## Changes
### API changes

N/A
### Behavioural changes

N/A
## Backwards compatibility

N/A
## Follow-up

Requires translations:

| Name | Value in eng.ini |
| :--: | :---: |
| `pocketmine.command.transferserver.description` | `Transfer someone to another server` |
| `pocketmine.command.transferserver.usage` | `/transferserver <server> [port] [player]` |

## Tests
Connect a second account and transfer it to a server of your choice. Works

2021-06-13 15:06 UTC, dktapps requested changes
There are a number of problems with this PR:
- It allows any player to transfer any other player, regardless of permissions.
- It doesn't properly handle invalid players. If a player is specified who's offline, an error message will be sent, and then the server will crash anyway.
- The formatting doesn't follow PocketMine-MP's code style.

2021-06-13 16:57 UTC, ShockedPlot7560 commented
> There are a number of problems with this PR:
> 
> * It allows any player to transfer any other player, regardless of permissions.
> * It doesn't properly handle invalid players. If a player is specified who's offline, an error message will be sent, and then the server will crash anyway.
> * The formatting doesn't follow PocketMine-MP's code style.

Change requested corrected normally in the previous commit

2021-06-13 18:47 UTC, dktapps commented on src/pocketmine/command/defaults/TransferServerCommand.php
> +			if (!$sender->hasPermission("pocketmine.command.transferserver.other")){
This permission doesn't exist. It needs to be defined in `DefaultPermissions`.

2021-06-13 18:47 UTC, dktapps commented on src/pocketmine/command/defaults/TransferServerCommand.php
> +			if (!$target instanceof Player || !$target->isOnline()){
getPlayer() will never return offline players.

2021-06-13 18:47 UTC, dktapps commented on src/pocketmine/command/defaults/TransferServerCommand.php
> +
Unrelated formatting change.

2023-05-29 20:31 UTC, dktapps commented
Closing this as stale due to lack of timely review - the code in this PR is now several years obsolete and would be better rewritten once PM5 is pushed to stable.

2023-05-29 20:31 UTC, closed without merging