implement dynamic inventory management
pmmp/PocketMine-MP pull request #4414
Opened 2021-08-29 11:27 UTC by HimmelKreis4865

## Introduction
This PR implements a dynamic inventory management, that simplifies sending and handling of new inventories, that are not yet implemented in pm4.

### Relevant issues
 - There is no issue related to this pull request

## Changes
### API changes
 - new class `pocketmine\inventory\InventoryFactory`
 - `InventoryFactory::getInstance()->register()` to register a new inventory

## Backwards compatibility
Backward compatible as long as there are no inventories that were previously implemented, which would now need to be registered.

## Tests
Implemented Grindstone successfully:
```php
InventoryFactory::getInstance()->register(GrindstoneInventory::class, WindowTypes::GRINDSTONE, UIInventorySlotOffset::GRINDSTONE);
```
GrindstoneInventory.php
```php
class GrindstoneInventory extends SimpleInventory implements BlockInventory {
	use BlockInventoryTrait;
	
	public function __construct(Position $position, int $size = 3) {
		$this->holder = $position;
		parent::__construct($size);
	}
}
```
In addition, I was still able to open all other inventories

2021-08-29 11:46 UTC, dktapps commented
This is mixing protocol into the API.

2021-08-29 11:54 UTC, HimmelKreis4865 commented
But isn't that still better than leaving that hardcoded, where no other inventories can be added? 
Or do you have a better idea for it?

2021-08-29 12:28 UTC, dktapps commented on src/inventory/InventoryFactory.php
> +final class InventoryFactory{
This doesn't belong in the `inventory` namespace. `network\mcpe` or `network\mcpe\convert` would be more appropriate.

2021-08-29 14:01 UTC, dktapps requested changes
Overall the concept looks OK. But the formatting needs work, naming is a confusing mess, and this isn't a perfect replacement for the old code.

2021-08-29 14:01 UTC, dktapps commented on src/network/mcpe/convert/InventoryFactory.php
> +		if (($type = $this->windowTypes[$inventory::class]) instanceof Closure) $type = $type($inventory);
This will break subclassed inventories.

2022-01-18 15:55 UTC, dktapps commented
Closing due to lack of activity on review comments.

2022-01-18 15:55 UTC, closed without merging