Implemented Lectern
pmmp/PocketMine-MP pull request #4708
Opened 2022-01-06 18:33 UTC by ipad54

## Introduction
Implemented Lectern

### Relevant issues
Original PR is https://github.com/pmmp/PocketMine-MP/pull/4467, but is was closed

## Changes
### Behavioural changes
N/A

## Tests
https://www.youtube.com/watch?v=lbory7FWuZw

2022-01-06 19:24 UTC, dktapps commented
This also needs to be added to `VanillaBlocks` and `StringToItemParser`.

2022-01-06 19:33 UTC, dktapps commented on src/block/Lectern.php
> +		return $this->book instanceof WritableBookBase ? clone $this->book : $this->book;
```suggestion
		return $this->book !== null ? clone $this->book : null;
```
for clearer reading

2022-01-06 19:33 UTC, dktapps commented on src/block/Lectern.php
> +		if($book instanceof WritableBookBase){
```suggestion
		if($book !== null){
```

2022-01-06 19:33 UTC, dktapps commented on src/block/tile/Lectern.php
> +		$this->book = VanillaItems::AIR();
You can use `null` to represent no book, same as the block.

2022-01-06 19:33 UTC, dktapps commented on src/block/tile/Lectern.php
> +		if(!$book instanceof WritableBookBase or $book->isNull()){
```suggestion
		if($book === null || $book->isNull()){
```

2022-01-06 19:33 UTC, dktapps commented on src/network/mcpe/handler/InGamePacketHandler.php
> +		if(!$world->isChunkLoaded($chunkX, $chunkZ) || !$world->isChunkGenerated($chunkX, $chunkZ) || $world->isChunkLocked($chunkX, $chunkZ)){
```suggestion
		if(!$world->isChunkLoaded($chunkX, $chunkZ) || $world->isChunkLocked($chunkX, $chunkZ)){
```
`isChunkGenerated()` is unnecessary; chunks which are not generated are also not loaded.

2022-01-06 19:33 UTC, dktapps commented on src/network/mcpe/handler/InGamePacketHandler.php
> +			if($this->player->getPosition()->distance($lectern->getPosition()) <= 15){
This check can be combined with the one above.

In addition, this should probably use `Player->canInteract()`.

2022-01-06 19:33 UTC, dktapps commented on src/network/mcpe/handler/InGamePacketHandler.php
> +				if($book instanceof WritableBookBase && count($book->getPages()) == $packet->totalPages && $packet->page >= 0 && $packet->page <= $packet->totalPages){
```suggestion
				if($book !== null && count($book->getPages()) === $packet->totalPages && $packet->page >= 0 && $packet->page < $packet->totalPages){
```

Off-by-one bug here. The page index should not be equal to the page count (the pages are zero-indexed).

2022-01-06 19:33 UTC, dktapps commented on src/block/tile/TileFactory.php
> +		$this->register(Lectern::class, ["Lectern", "minecraft:lectern"]);
Alphabetical order.

2022-01-06 19:33 UTC, dktapps commented on src/block/BlockFactory.php
> +		$this->registerAllMeta(new Lectern(new BID(Ids::LECTERN, 0, ItemIds::LECTERN, TileLectern::class), "Lectern", new BlockBreakInfo(2.5, BlockToolType::AXE)));
Alphabetical order (this should be above `Lever`).

2022-01-06 21:41 UTC, JavierLeon9966 requested changes

2022-01-06 21:41 UTC, JavierLeon9966 commented on src/block/tile/Lectern.php
> +			if($book instanceof WritableBookBase){
```suggestion
			if($book instanceof WritableBookBase && !$book->isNull()){
```

2022-01-06 21:41 UTC, JavierLeon9966 commented on src/block/tile/Lectern.php
> +		$nbt->setByte(self::TAG_HAS_BOOK, $this->book !== null && !$this->book->isNull() ? 1 : 0);
```suggestion
		$nbt->setByte(self::TAG_HAS_BOOK, $this->book !== null ? 1 : 0);
```

2022-01-06 21:41 UTC, JavierLeon9966 commented on src/block/tile/Lectern.php
> +		return $this->book !== null && !$this->book->isNull() ? $this->book : null;
```suggestion
		return $this->book !== null ? clone $this->book : null;
```

2022-01-06 21:41 UTC, JavierLeon9966 commented on src/block/tile/Lectern.php
> +		$this->book = $book;
```suggestion
		$this->book = $book !== null && !$book->isNull() ? clone $book : null;
```

2022-01-06 21:41 UTC, JavierLeon9966 commented on src/block/tile/Lectern.php
> +		$nbt->setByte(self::TAG_HAS_BOOK, $this->book !== null && !$this->book->isNull() ? 1 : 0);
```suggestion
		$nbt->setByte(self::TAG_HAS_BOOK, $this->book !== null ? 1 : 0);
```

2022-01-06 22:07 UTC, JavierLeon9966 requested changes

2022-01-06 22:07 UTC, JavierLeon9966 commented on src/block/Lectern.php
> +		$this->book = $book;
```suggestion
		$this->book = $book !== null && !$book->isNull() ? (clone $book)->setCount(1) : null;
```
And you can remove the `if` statement from above

2022-01-06 22:07 UTC, JavierLeon9966 commented on src/block/Lectern.php
> +		if($this->book !== null && !$this->book->isNull()){
```suggestion
		if($this->book !== null){
```

2022-01-15 16:14 UTC, dktapps commented
The collision box height in Bedrock is 0.9 blocks tall. The PR hasn't accounted for this.

2022-01-15 16:18 UTC, dktapps commented
The hardness is also incorrect: it's 2.0 in Bedrock.

2022-01-15 17:17 UTC, dktapps commented
The book must be included in the drops (for example, in case of explosions).

2022-01-15 17:39 UTC, dktapps commented
A block will be placed if right-clicking on a lectern while holding a block. This isn't supposed to happen.

2022-01-15 21:21 UTC, merged