Implemented StoneCutter Block
pmmp/PocketMine-MP pull request #4732
Opened 2022-01-16 17:25 UTC by ipad54

## Introduction
Implemented StoneCutter Block

## Changes
### API changes
Added $blockType property to ShapelessRecipe
Added getBlockType() method to ShapelessRecipe

### Behavioural changes
N/A

## Follow-up
N/A

## Tests
https://youtu.be/HNuWtTHMf3s

2022-01-16 22:58 UTC, arfush commented
If some player breaks stonecutter?
Items will disappear forever. Yes? I'm sure of it

2022-01-17 01:36 UTC, dktapps commented
Actually it won't: https://github.com/pmmp/PocketMine-MP/pull/4732/files#diff-adf08eca6b5de3fb8b72b57f0c8223b70b29f5b1fd8314619282f7e9f8c7b5f5R30

2022-01-18 16:21 UTC, hausemaster3734 commented
> Actually it won't: https://github.com/pmmp/PocketMine-MP/pull/4732/files#diff-adf08eca6b5de3fb8b72b57f0c8223b70b29f5b1fd8314619282f7e9f8c7b5f5R30

What this means?

2022-01-18 18:42 UTC, dktapps requested changes

2022-01-18 18:42 UTC, dktapps commented on src/block/StoneCutterBlock.php
> +class StoneCutterBlock extends Transparent{
This should simply be `Stonecutter`.

2022-01-18 18:42 UTC, dktapps commented on src/block/inventory/StoneCutterInventory.php
> +	public const SLOT_OUTPUT = 1;
The output isn't a real slot, same as for crafting.

2022-01-18 18:42 UTC, dktapps commented on src/crafting/CraftingManagerFromDataHelper.php
> +			$blockType = match ($recipe["block"]){
This leaks protocol info into the API. An enum should be added for this similar to FurnaceType.

2022-01-18 18:42 UTC, dktapps commented on src/block/inventory/StoneCutterInventory.php
> +class StoneCutterInventory extends SimpleInventory implements BlockInventory, TemporaryInventory{
This should be `StonecutterInventory`.

2022-01-18 18:42 UTC, dktapps commented on src/block/VanillaBlocks.php
> +		self::register("stonecutter_block", $factory->get(452, 0));
`_block` is redundant. We know it's a block already or we wouldn't be using `VanillaBlocks`.

2022-01-18 18:42 UTC, dktapps commented on src/block/BlockFactory.php
> +		$this->registerAllMeta(new StoneCutterBlock(new BID(Ids::STONECUTTER_BLOCK, 0, ItemIds::STONECUTTER_BLOCK), "Stonecutter Block", new BlockBreakInfo(3.5, BlockToolType::PICKAXE)));
`Block` suffix is unnecessary.

2022-01-18 18:43 UTC, dktapps commented on src/block/BlockFactory.php
> +		$this->registerAllMeta(new StoneCutterBlock(new BID(Ids::STONECUTTER_BLOCK, 0, ItemIds::STONECUTTER_BLOCK), "Stonecutter Block", new BlockBreakInfo(3.5, BlockToolType::PICKAXE)));
This is also in the wrong place. Please learn how alphabetical order works.

2022-01-18 18:54 UTC, dktapps commented
This is also missing from StringToItemParser.

2022-01-21 00:11 UTC, dktapps commented on src/network/mcpe/cache/CraftingDataCache.php
> +					$recipe->getBlockType()->name(),
This is not guaranteed to match the network name.

2022-01-22 17:18 UTC, dktapps commented
IIRC, there is a sound when crafting stuff using a stonecutter. It's missing from the PR.

2022-01-22 17:25 UTC, dktapps commented
The block doesn't face in the correct direction when placed facing east or west. You need to use `readHorizontalFacing` instead of `readLegacyHorizontalFacing`, and a state bitmask of `0b111` instead of `0b11`.

2022-01-22 17:28 UTC, dktapps commented
> > Actually it won't: https://github.com/pmmp/PocketMine-MP/pull/4732/files#diff-adf08eca6b5de3fb8b72b57f0c8223b70b29f5b1fd8314619282f7e9f8c7b5f5R30
> 
> What this means?

It means that [this person](https://github.com/pmmp/PocketMine-MP/pull/4732#issuecomment-1013970137) has no idea what they were talking about.

2022-01-22 17:33 UTC, dktapps commented
Apart from a couple of bugs and minor issues, this PR basically "just works", so it's in pretty good shape already. There's some discussion to be had about API design, but the PR is overall looking OK.

2022-01-22 17:34 UTC, dktapps commented on src/block/Stonecutter.php
> +		return [AxisAlignedBB::one()->trim(Facing::UP, 0.5)];
This is incorrect. The height is actually 9/16, so it should be trimmed by 7/16.

2022-01-22 20:10 UTC, dktapps commented
CS checks are failing because there should be an empty line at the end of every file. You can either fix it manually or run php-cs-fixer locally to fix it.

2022-01-22 20:38 UTC, dktapps commented on src/item/StringToItemParser.php
>  		$result->registerBlock("stonecutter", fn() => VanillaBlocks::LEGACY_STONECUTTER());
I think we can change this to use the new stonecutter as well. Might be worth adding a `legacy_stonecutter` alias for the old one, though.

2022-01-22 20:38 UTC, dktapps commented on src/crafting/CraftingBlockType.php
> +final class CraftingBlockType{
I don't really think `block type` is a suitable expression for this. Most of these recipes work on the 2x2 crafting grid, which isn't a block at all.

2022-01-23 17:01 UTC, dktapps commented on src/crafting/CraftingBlockType.php
> +final class CraftingBlockType{
I think `ShapelessRecipeType` would probably suit better. Its members would be `CRAFTING` and `STONECUTTER`.

2022-01-25 19:03 UTC, dktapps commented on src/crafting/ShapelessRecipe.php
> +	public function __construct(array $ingredients, array $results, ?ShapelessRecipeType $recipeType = null){
Please put a TODO in the doc comment here -  we'll want to make the `recipeType` parameter mandatory in PM5.

Also, I think we can refer to it as just `type`, given the context.

2022-01-25 19:03 UTC, dktapps commented on src/crafting/ShapelessRecipe.php
> +		return $this->recipeType;
This could simply be `type` rather than `recipeType`. Similar goes for the method name.

2022-01-25 19:06 UTC, dktapps commented
For posterity I'll mention it here: there's currently no verification for whether the crafted recipe was actually crafted using a stonecutter. In addition, this allows non-stonecutter recipes to be used on a stonecutter.

That said, this problem also exists elsewhere with big/small crafting recipes lacking verification, since it only cares if you have the right number of ingredients.

This isn't a terribly harmful or useful exploit, but it may allow you to obtain some materials that you otherwise wouldn't be able to in early game.

2022-05-17 14:55 UTC, dktapps commented on src/crafting/CraftingManagerFromDataHelper.php
> +			$recipeType = match ($recipe["block"]){
```suggestion
			$recipeType = match($recipe["block"]){
```

2022-05-17 15:01 UTC, merged