Implement Bonemeal for TallGrass
pmmp/PocketMine-MP pull request #4757
Opened 2022-01-23 02:06 UTC by DuoIncure

## Introduction
Added functionality for Bonemeal to work on regular and fern versions of TallGrass.

## Tests
[Video](https://streamable.com/mxscbm)

2022-01-23 02:15 UTC, JavierLeon9966 requested changes

2022-01-23 02:15 UTC, JavierLeon9966 commented on src/block/TallGrass.php
> +			$blockAbove = $this->getPosition()->getWorld()->getBlockAt((int)$this->position->x, (int)$this->position->y + 1, (int)$this->position->z);
```suggestion
			$blockAbove = $this->position->getWorld()->getBlock($this->position->up());
```

2022-01-23 02:15 UTC, JavierLeon9966 commented on src/block/TallGrass.php
> +		if($down === BlockLegacyIds::GRASS || $down === BlockLegacyIds::DIRT || $down === BlockLegacyIds::FARMLAND || $down === BlockLegacyIds::PODZOL || $down === BlockLegacyIds::MYCELIUM){
This change is unrelated

2022-01-23 02:15 UTC, JavierLeon9966 commented on src/block/TallGrass.php
> +		if($this->getSide(Facing::DOWN)->isTransparent()){
This change is unrelated

2022-01-23 02:15 UTC, JavierLeon9966 commented on src/block/TallGrass.php
> +				$this->position->getWorld()->setBlock($this->getSide(Facing::UP)->getPosition(), $doubleBlock->setTop(true), true);
```suggestion
				$this->position->getWorld()->setBlock($this->position->up(), $doubleBlock->setTop(true), true);
```

2022-01-26 00:19 UTC, dktapps commented
This PR should be split up. Please don't submit multiple unrelated changes in one PR.

2022-01-27 17:09 UTC, closed without merging

2022-01-27 17:10 UTC, dktapps commented
Closing due to combination of changes. Please resubmit the changes in separate PRs.