Implement Head Yaw in a way that doesn't break BC.
pmmp/PocketMine-MP pull request #4819
Opened 2022-02-11 04:54 UTC by TheBlackPlague

## Introduction

Currently, PM doesn't really consider head-yaw to be a property. This can be tedious/nearly impossible when you want to change head-yaw without messing directly with the protocol. 

### Relevant issues

- There isn't really an issue for this.

## Changes
### API changes

Location now supports a property `headYaw`. The property is strictly of type `float`. The constructor accepts this as an optional argument. All methods used to change the rotation of an entity also use the `headYaw` property if set. Furthermore, all methods mentioned above accept this as an optional argument. 

### Behavioural changes

The server should continue to behave the same way. If no `headYaw` is provided, then by default, the player's `yaw` is substituted in.

## Backwards compatibility

To preserve BC, the argument has been added in as optional to all methods. Meaning plugins or internal functions not supplying a `headYaw` argument to either the constructor or changed methods will continue to work the same way with no behavior change. If they provide the optional field, they'll be able to use it. 

A possible issue is the methods extending the `Location` class. They might need to update the relevant signature for their constructor. A possible fix for this issue is by removing it from a constructor and adding it as a function-based setter.

## Tests

This adds a property that doesn't break any internal BC. Henceforth, it doesn't necessarily need to be tested as it behaves the same way.

2022-02-11 17:39 UTC, dktapps commented
I'm doubtful this should be in Location, since Location is generic for all entities, but objects such as arrows don't have head yaw.

2022-02-11 17:45 UTC, JavierLeon9966 requested changes
You forgot to pass `$headYaw` in some functions so here’s a list including this one: https://github.com/pmmp/PocketMine-MP/blob/00717e15d4762ca93ad4a991062b343e2e75a14d/src/player/Player.php#L2358

2022-02-11 17:45 UTC, JavierLeon9966 commented on src/player/Player.php
>  		$this->getNetworkSession()->syncMovement($pos, $yaw, $pitch, $mode);
```suggestion
		$this->getNetworkSession()->syncMovement($pos, $yaw, $pitch, $mode, $headYaw);
```

2022-02-11 17:45 UTC, JavierLeon9966 commented on src/player/Player.php
>  		if(parent::teleport($pos, $yaw, $pitch)){
```suggestion
		if(parent::teleport($pos, $yaw, $pitch, $headYaw)){
```

2022-02-11 21:14 UTC, TheBlackPlague commented
> I'm doubtful this should be in Location, since Location is generic for all entities, but objects such as arrows don't have head yaw.

Where do you suggest it should be then? In Entity, I presume then? Or in the Human?

2022-02-11 21:16 UTC, dktapps commented
All entities descend from Entity, that's no better than Location.

I would suggest Living, but it's kinda awkwardly placed in there and there's a lot more needs to be done to properly support it (e.g. lookAt() needs to be aware of it).

2022-02-11 21:20 UTC, TheBlackPlague commented
> All entities descend from Entity, that's no better than Location.
> 
> I would suggest Living, but it's kinda awkwardly placed in there and there's a lot more needs to be done to properly support it (e.g. lookAt() needs to be aware of it).

I can implement such in Living, that shouldn't be an issue, along with making `lookAt()` aware of it. Would you be able to give me a list of methods that use the yaw in a way that headYaw would be a better use? That would speed up my development time a lot.

2022-02-11 21:25 UTC, JavierLeon9966 commented
Also `getDirectionVector()`

2022-02-11 21:25 UTC, TheBlackPlague commented
Furthermore, I am also unsure why all the variables in Location/Vector3 remain public— there should be Gettes and Setters for those methods. Ensuring BC becomes 10x harder if methods are publicized unnecessarily. 

A way to counter this is using the `Magic Methods` (`__set()` and `__get()`). Your thoughts @dktapps ?

2022-02-11 21:27 UTC, dktapps commented
I think it's pointless. This whole yarn about BC is nonsense. __get() and __set() exist exactly for the purpose of avoiding BC breaks. Adding them at this point serves no advantage. In addition, the fields of Location and Vector3 should not be mutable, so we don't want setters anyway. But that's outside the scope of this PR.

2022-02-11 21:29 UTC, dktapps commented
I think it's also worth mentioning that one of the reasons why Vector3 in particular continues to have public members is because it's used in hot pathways in the core code. I don't like having them public (or, more accurately, I don't like having them _mutable_), but it's currently a tradeoff that I feel ok about making.

2022-02-13 01:18 UTC, TheBlackPlague commented
After further discussion with @dktapps , it was decided that this cannot be reasonably implemented in a way that's good for the code-base & is backward compatible. What this means is that there is a good chance this will be in `5.0.0` (the next major release), but it will not be in any `4.x.x` (minor releases).

2024-08-20 10:05 UTC, ShockedPlot7560 commented on src/entity/Entity.php
> +			}
Already done in setRotation, no need to write again

2024-08-20 10:05 UTC, ShockedPlot7560 commented on src/entity/Entity.php
> +			/** @noinspection CallableParameterUseCaseInTypeContextInspection - This will never happen. */
this noinspection comment has no place to be here

2024-08-20 10:05 UTC, ShockedPlot7560 commented on src/entity/Location.php
> +	public $headYaw;
HeadYaw has no place to be in Location.

2024-08-20 10:05 UTC, ShockedPlot7560 commented
Need to target next-minor

2024-08-20 10:05 UTC, ShockedPlot7560 commented
Oops, missclick on close

2024-08-20 10:17 UTC, dktapps commented
The PR is very stale, might as well close it and open a tracking issue instead

2024-11-14 15:17 UTC, closed without merging