[Fix] ItemEntity bounces on Slime Block
pmmp/PocketMine-MP pull request #5095
Opened 2022-06-05 18:55 UTC by Swift-Strider

## Introduction

This PR fixes items previously not bouncing on slime blocks.

### Relevant issues

* Fixes #4830

## Changes
Items now bounce on slime blocks.
### API changes

No significant API changes, as `onHitGround()` was only overriden. It may break plugins that depend on ItemEntity's previous behavior of landing without calling `$fallBlock->onEntityLand()`.

### Behavioural changes

Items now bounce on slime blocks.

## Backwards compatibility

This is a backwards compatible change.
## Follow-up
Perhaps moving generic physics code and applying that to ItemEntity, armor_stand, etc.

## Tests
I haven't added any tests.

2022-09-20 15:26 UTC, jasonwynn10 requested changes
I think the code for calling `Block::onEntityLand()` should be moved from Living to Entity while leaving the fall damage code in Living instead of creating boilerplate for this use case.

2022-09-21 11:42 UTC, dktapps commented
> I think the code for calling `Block::onEntityLand()` should be moved from Living to Entity while leaving the fall damage code in Living instead of creating boilerplate for this use case.

You might be right about this, but it might have other unintended consequences, e.g. bouncy XP orbs, bouncy arrows, etc.

2022-09-27 13:58 UTC, ColinHDev commented
And limiting the affected entities in the [`Slime` class](https://github.com/pmmp/PocketMine-MP/blob/next-minor/src/block/Slime.php) itself?

2024-03-21 07:11 UTC, ShockedPlot7560 commented on src/entity/object/ItemEntity.php
> +			$fallBlock = $this->getWorld()->getBlock($fallBlockPos);
So, if the down block has no collision too, it will stop here, no ?

2024-11-14 15:31 UTC, dktapps commented
> And limiting the affected entities in the [`Slime` class](https://github.com/pmmp/PocketMine-MP/blob/next-minor/src/block/Slime.php) itself?
> 
> The `Block::onEntityLand()` already has it in its name: It's supposedly called once an entity lands on it. So every block extending that method should decide for themselves to which entities they want to limit their behaviour.

Yeah, this is probably the correct fix.

However this PR is very stale so I'm going to close it.

2024-11-14 15:31 UTC, closed without merging