Fix Kor Language(kor - locale)
pmmp/PocketMine-MP pull request #51
Opened 2016-10-25 13:28 UTC by ParkChanSol

2016-10-25 16:40 UTC, pillose commented
language_has_been_selected = 한국어가 언어로 선택되었습니다.
skip_installer = 설치 마법사를 건너뛰겠습니까?

welcome_to_pocketmine = PocketMine-MP에 오신 것을 환영합니다!\n서버 설치를 시작하기 전, 약관에 동의해야 합니다. \nPocketMine-MP는 GNU 약소 일반 공중 사용 허가서(LGPL) 하에 배포되고 있습니다. \n이 폴더에서 약관을 읽을 수 있습니다.
accept_license = 약관에 동의하십니까?
you_have_to_accept_the_license = GNU 약소 일반 공중 사용 허가서(LGPL)에 동의하셔야 PocketMine-MP를 사용할 수 있습니다.

setting_up_server_now = 서버 설정을 시작합니다.
default_values_info = 기본값을 수정하고 싶지 않으면, 엔터를 `누르시기` 바랍니다.
server_properties = 이 설정들은 server.properties 파일에서 세부적으로 변경이 가능합니다.

name_your_server = 당신의 서버 이름을 입력하시기 바랍니다.
port_warning = 만약 당신이 서버를 처음 설정한다면 포트 값을 변경하지 마세요.
server_port = 서버 포트
invalid_port = 서버 포트가 잘못 입력되었습니다.
ram_warning = RAM 값은 PocketMine-MP에 할당할 메모리의 크기입니다. 128~256MB를 권장합니다.
server_ram = 서버의 램(RAM) (MB)
gamemode_info = 크리에이티브 (1) 또는 서바이벌 (0) 게임모드 중 하나를 고르세요.
default_gamemode = 기본 게임 모드
max_players = 최대 동시 접속 인원수
spawn_protection_info = 스폰 보호는 OP를 제외한 유저들이 스폰 지역 근처에서 `블록을` 놓거나 부수는 것을 방지합니다.
spawn_protection = 스폰 지역 보호를 사용하겠습니까?

op_info = OP는 서버 관리자를 뜻합니다. OP는 일반 플레이어보다 훨씬 많은 명령어들을 사용할 수 있습니다
op_who = OP 권한을 줄 플레이어 이름(예: 당신의 닉네임)
op_warning = 또는 이후에 /op <플레이어 이름> 을 입력해 그 유저에게 OP 권한을 줄 수도 있습니다
whitelist_info = `화이트 리스트를` 사용하면 허용된 플레이어들만 서버에 접속할 수 있습니다.
whitelist_enable = `화이트 리스트를` 사용하겠습니까?
whitelist_warning = 당신은 접속을 허용할 플레이어들의 이름을 적어야 합니다

query_warning1 = 쿼리 (Query)는 당신의 서버와 현재 접속한 플레이어들의 정보를 알 수 있게 해주는 `여러 가지` 기능이 담긴 프로토콜입니다.
query_warning2 = 쿼리를 사용하지 않으면, 당신은 서버 리스트를 사용할 수 없게 됩니다.
query_disable = 쿼리를 사용하지 않겠습니까?
rcon_info = RCON은 `비밀번호를` 사용하여 서버 명령창에 원격으로 접속할 수 있는 프로토콜입니다.
rcon_enable = RCON 을 사용하시겠습니까?
rcon_password = RCON 비밀번호 설정 (나중에 server.properties 에서 변경이 가능합니다.)
usage_info = 익명 사용 통계 전송을 허용하면 PocketMine-MP가 세계의 서버 상황과 플러그인들을 통계화하는 데 사용할 수 있습니다. 당신은 stats.pocketmine.net에서 이를 확인할 수 있습니다
usage_disable = 익명 사용 통계 전송을 사용하지 않으시겠습니까?
ip_get = 내/외부 IP 주소 얻기
ip_warning = 당신의 외부 IP는 {{EXTERNAL_IP}}입니다. 당신의 내부 IP {{INTERNAL_IP}}로 포트포워딩이 필요할 수 있습니다.
ip_confirm = 신중하게 확인하세요. 만약 포트 포워딩이 필요하지만 하지 않을 경우 외부에서 플레이어들이 접속할 수 없게 됩니다. [`계속하시려면` 엔터를 누르세요]

you_have_finished = PocketMine-MP의 설치가 모두 완료되었습니다.
pocketmine_will_start = PocketMine-MP 서버를 구동합니다. /help로 사용 가능한 모든 명령어의 목록을 보시기 바랍니다.
pocketmine_plugins = 플러그인 저장소에서 새로운 기능을 추가하세요. 새로운 기능, 미니게임을 추가하거나 고급 기능으로 당신의 서버를 보호할 수 있습니다

2016-10-26 09:22 UTC, SOF3 commented
@pillose I don't understand what you are trying to do with your comment.

2016-10-26 13:33 UTC, ghost approved these changes

2016-10-26 13:46 UTC, nnnlog reviewed
Ok,

2016-10-26 16:04 UTC, hiilikewiki approved these changes

2016-10-26 16:36 UTC, pillose requested changes
On line 9:누르십시기 > 누르시기
thank you

2016-10-27 08:56 UTC, nnnlog reviewed
I approve line 9

2016-10-27 14:26 UTC, SOF3 commented
@ParkChanSol please stop spamming. You shouldn't have submitted the pull request in the first place if you didn't approve it.

2016-10-27 15:07 UTC, pillose approved these changes

2016-10-27 15:48 UTC, archie426 commented
Please just stop spamming this. THERE IS NO EXCUSE. @SOF3, if they do any more, you should block them

2016-10-30 08:39 UTC, JellyBrick commented
@SOF3 This PR solved a grammatical error.

2016-11-12 10:46 UTC, ParkChanSol commented
@SOF3 When check(merge or close) this PR

2016-12-01 13:21 UTC, closed without merging

2016-12-01 13:25 UTC, ParkChanSol commented
@dktapps Why you close this PR?

2016-12-01 13:26 UTC, dktapps commented
https://translate.pocketmine.net