Improve performance of `InventoryManager::syncCreative()`
pmmp/PocketMine-MP pull request #5118
Opened 2022-06-28 05:46 UTC by Nerahikada

## Introduction
I found that it is taking a long time to change the game mode of the player.
This is due to the time taken to generate the CreativeContentPacket.
This PR improves the performance of `InventoryManager::syncCreative()` by caching the packet.

### Relevant issues
N/A

## Changes
### API changes
N/A

## Backwards compatibility
N/A

## Tests
Reduced from about 100 milliseconds to 0.7 milliseconds.
```php
$startTime = microtime(true);
for($i = 0; $i < 10; ++$i){
	$_player->setGamemode(GameMode::SURVIVAL());
	$_player->setGamemode(GameMode::CREATIVE());
}
$time = microtime(true) - $startTime;
$_player->sendMessage(round($time * 10 ** 3, 1) . "ms");
```

2022-06-28 21:33 UTC, dktapps commented on src/inventory/CreativeInventory.php
> +	public function getContentPacket() : CreativeContentPacket{
This should not be in the API.

2022-08-14 17:08 UTC, dktapps requested changes
This method wastes memory and the cache invalidation doesn't work correctly.

2022-08-14 17:08 UTC, dktapps commented on src/network/mcpe/InventoryManager.php
> +			$creativeInventory->setChanged(false);
If the creative inventory is modified while there are players online, this will cause the changes to be synced only for the first one.

2022-08-16 09:39 UTC, Nerahikada commented
I don't have enough time to work on this. I will open the issue for posterity.

2022-08-16 09:39 UTC, closed without merging

2022-08-16 12:50 UTC, dktapps commented
> I don't have enough time to work on this. I will open the issue for posterity.

Thank you.

2023-04-18 11:27 UTC, dktapps commented
Related PR: #5703