Implement Sub-MOTD Feature
pmmp/PocketMine-MP pull request #5290
Opened 2022-09-15 08:42 UTC by xqwtxon

## Introduction
Introducing, Custom Sub-MOTD Support as on Custom MOTD in the config. This changes the interface query of the server.

### Relevant issues
* Sub-MOTD Support (#5204)

## Changes
### API changes
```php
Network->setName("MOTD", "Sub-MOTD");
```

### Behavioural changes
It change the query interface, might included in `QueryInfo`

## Backwards compatibility
```php
$this->getServer()->getNetwork()->setName("MOTD", "Sub-MOTD");

$this->getServer()->getMotd();
$this->getServer()->getSubMotd();
```

## Follow-up
* Test the server and run with **example plugin test** for this feature.

## Tests
* [Plugin Test](https://github.com/xqwtxon/SubMotd-TestPlugin)

2022-09-15 08:54 UTC, xqwtxon commented
Sorry, if my commit is unverified, i havent setup yet my gpg key.

2022-09-15 09:28 UTC, NhanAZ commented on src/PocketMine.php
> +		}*/
Why did you put this in the comment?

2022-09-15 09:28 UTC, NhanAZ commented on tests/phpunit/block/BrewingStandTest.php
> +use function array_values;
This has nothing to do with PR

2022-09-15 11:10 UTC, xqwtxon commented on src/PocketMine.php
> +		}*/
oh my mad

2022-09-15 11:13 UTC, xqwtxon commented on tests/phpunit/block/BrewingStandTest.php
> +use function array_values;
I hate php-cs-fixer dryrun ๏_๏

2022-09-17 07:13 UTC, Endermanbugzjfc commented
What is a “sub-MOTD”?

2022-09-17 07:32 UTC, NhanAZ commented
> What is a “sub-MOTD”?

https://github.com/pmmp/PocketMine-MP/issues/5204

2022-09-17 07:39 UTC, Endermanbugzjfc commented
> > What is a “sub-MOTD”?
> 
> 
> 
> https://github.com/pmmp/PocketMine-MP/issues/5204

Thanks.

2022-09-17 11:56 UTC, Gaprix approved these changes

2022-09-17 16:46 UTC, dktapps requested changes
As before, the documentation available for this feature is inadequate. Most of the time, people won't even see this text, so they'll think something is broken when it doesn't appear to change anything.

2022-09-19 21:34 UTC, matcracker commented
Since this MOTD is only shown in the "LAN" page list, wouldn't it be better to call the parameter as "lan-motd"? At first not knowing what the sub-motd was, I was expecting a message under the current MOTD instead it only concerns the LAN screen.

2022-09-20 07:14 UTC, xqwtxon commented
> Since this MOTD is only shown in the "LAN" page list, wouldn't it be better to call the parameter as "lan-motd"? At first not knowing what the sub-motd was, I was expecting a message under the current MOTD instead it only concerns the LAN screen.

Good idea :)

2022-09-20 09:12 UTC, xqwtxon commented
For Developers:

Please do not use `Network->internalSetName()` It breaks backwards compabilities. If you want to improve this or change this, please kindly make it at your own.If you want to help us, please kindly created your own pull requests.

2022-09-22 12:21 UTC, xqwtxon commented
Also, i found more links about the pull requests, such as forum and other pull requests.

2022-09-22 12:23 UTC, xRodzMC commented on src/PocketMine.php
> +		}*/
fixed

2022-09-26 04:33 UTC, xqwtxon commented
My commits are advance time, sorry but time havent configured yet.

2022-09-28 17:09 UTC, dktapps commented
This PR has taken up way too much time and effort to be worthwhile for such a small change. It's also now venturing into BC-break territory since it adds new requirements to the NetworkInterface interface. In addition, the author seems unwilling or unable to address review comments, so I'm going to close this.

2022-09-28 17:09 UTC, closed without merging

2022-09-29 11:15 UTC, xqwtxon commented
> This PR has taken up way too much time and effort to be worthwhile for such a small change. It's also now venturing into BC-break territory since it adds new requirements to the NetworkInterface interface. In addition, the author seems unwilling or unable to address review comments, so I'm going to close this.

Sorry, i have enough time to do work with it, Since i was busy...