Fix missing sounds when interacting with item frames
pmmp/PocketMine-MP pull request #5383
Opened 2022-11-02 20:30 UTC by zSALLAZAR

## Introduction

### Relevant issues

#5168 

## Changes
### API changes

### Behavioural changes

## Backwards compatibility

## Follow-up

## Tests

https://user-images.githubusercontent.com/59490940/199596126-a545f8cc-c153-4112-a344-55cbea54ea20.mp4

2022-11-02 20:33 UTC, JavierLeon9966 requested changes

2022-11-02 20:33 UTC, JavierLeon9966 commented on src/network/mcpe/handler/InGamePacketHandler.php
> +			$this->player->getWorld()->addSound($pos = new Vector3($blockPosition->getX(), $blockPosition->getY(), $blockPosition->getZ()), new ItemFrameRemoveItemSound());
This should be in `ItemFrame->onAttack()`, you don't know if the item frame is empty

2022-11-02 20:35 UTC, JavierLeon9966 commented on src/network/mcpe/handler/InGamePacketHandler.php
> +			$this->player->getWorld()->addSound($pos = new Vector3($blockPosition->getX(), $blockPosition->getY(), $blockPosition->getZ()), new ItemFrameRemoveItemSound());
Now that I see that code above it it does check, but you don't know if a plugin has canceled the interact action

2022-11-02 20:55 UTC, zSALLAZAR commented on src/network/mcpe/handler/InGamePacketHandler.php
> +			$this->player->getWorld()->addSound($pos = new Vector3($blockPosition->getX(), $blockPosition->getY(), $blockPosition->getZ()), new ItemFrameRemoveItemSound());
You're right
I'll change it tomorrow

2022-11-07 13:47 UTC, dktapps commented on src/block/ItemFrame.php
> +			$this->position->getWorld()->addSound($this->position, new ItemFrameRemoveSound());
`ItemFrameDestroySound` would be more consistent, though I don't see why item frames need a dedicated sound for this. We don't play specific destroy sounds or particles for nearby updates for any other block.

2022-11-07 13:48 UTC, dktapps commented
Retargeting this to next-minor since it's adding new APIs.

2022-11-07 15:31 UTC, zSALLAZAR commented on src/block/ItemFrame.php
> +			$this->position->getWorld()->addSound($this->position, new ItemFrameRemoveSound());
If you remove the block behind the itemframe in vanilla a itemframe destroy sound is played, but not in Pocketmine, so I added this sound.

2022-11-25 14:27 UTC, dktapps commented
I've removed the onNearbyBlockChange changes since those don't directly pertain to interaction, and the missing sounds there are part of a larger issue which should be solved in a more generic way. The rest of the PR is good to merge though.

2022-11-25 14:28 UTC, merged