Add missing sounds when equipping or unequipping armour using right-c…
pmmp/PocketMine-MP pull request #5416
Opened 2022-11-16 10:33 UTC by zSALLAZAR

…lick

## Introduction

### Relevant issues

#5167 

## Changes
### API changes

### Behavioural changes

## Backwards compatibility

## Follow-up

## Tests

https://user-images.githubusercontent.com/59490940/202156971-89b2d3e7-b24a-4711-b335-b52f18e415cd.mp4

2022-11-17 15:52 UTC, NhanAZ commented
Looks like the sound of Netherite armor is missing

2022-11-17 16:58 UTC, zSALLAZAR commented
> Looks like the sound of Netherite armor is missing

Yeah, but Netherite is not implemented in stable

2022-11-17 17:09 UTC, NhanAZ commented
I didn't look at the branch 💀 
I think you should move this pull request to branch `next-major`
https://github.com/pmmp/PocketMine-MP/blob/stable/CONTRIBUTING.md#choosing-a-target-branch

2022-11-17 17:28 UTC, zSALLAZAR commented
You sure? I think I should change the targeting branch to next-minor because I only added new API classes

2022-11-17 19:45 UTC, dktapps commented
next-minor is fine

2022-12-06 12:55 UTC, dktapps requested changes

2022-12-06 12:55 UTC, dktapps commented on src/item/Armor.php
> +			default => null
This is an awful mess. There has to be a better way to do this.

2023-03-17 15:23 UTC, jasonw4331 approved these changes

2023-03-27 19:37 UTC, dktapps commented on src/item/Armor.php
> +	public function setEquipSound(?Sound $equipSound) : self{
This should be removed. We don't persist this information, so it's going to vanish after a restart.

2023-08-07 13:10 UTC, dktapps approved these changes

2023-08-31 08:16 UTC, ShockedPlot7560 commented
Is merge planned?

2023-09-01 10:17 UTC, dktapps commented
Yes, but I'll need to re-review it once the branches are in sync

2023-09-11 17:20 UTC, zSALLAZAR commented
I think it would be better if we add the equip sounds to `src/item/ArmorMaterial.php` to prevent duplication, as also mentioned in https://github.com/pmmp/PocketMine-MP/pull/5953#issue-1829965310

2023-09-13 12:54 UTC, dktapps commented
Yeah, I agree

2024-03-25 14:21 UTC, ShockedPlot7560 commented
Superseeded by https://github.com/pmmp/PocketMine-MP/commit/f799cfaba6318dcf90fce3956bb4843d12581df2

2024-03-25 14:21 UTC, closed without merging