Implement DataPacketPreReceiveEvent
pmmp/PocketMine-MP pull request #5559
Opened 2023-02-08 04:11 UTC by Cosmic5173

## Introduction
As said in #5554, some packets do not need to go through the decoding process. This implements an event that allows a set of ignored packets to be set. These packets will be intercepted and denied decoding if they are flagged as ignored.

### Relevant issues
Closes #5554 

## Changes
### API changes
Creation of the event ``pocketmine\event\server\DataPdacketPreReceiveEvent``

### Behavioural changes
Some packets are not decoded, therefore not handled. Some sort of performance gain should be expected.

## Tests
```php
class Main extends PluginBase implements Listener{

	public function onEnable(): void{
		$this->getServer()->getPluginManager()->registerEvents($this, $this);
	}

	public function onPreDataPacketReceiveEvent(DataPacketPreReceiveEvent $event): void{
		$packets = $event->getIgnoredPackets();
		$packets[] = ProtocolInfo::INVENTORY_TRANSACTION_PACKET;
		$event->setIgnoredPackets($packets);
	}
}
```
A plugin that flags the ``Inventory Transaction Packet`` as "ignored". All inventory actions (i.e dropping items) are never handled by the server.

2023-02-08 04:51 UTC, IvanCraft623 commented
This should be targeted to `next-major` since it contains BC-Break

2023-02-08 05:47 UTC, JavierLeon9966 commented
I don't see any BC breaks for my part, just behavior changes. For example, plugins will no longer receive `LevelSoundEventPacket`s' for cps

2023-02-08 10:08 UTC, dktapps requested changes
This is rather more complex than I'd envisioned. My thought was to pass the packet buffer string to the event directly, which would allow plugins to decide how to handle it, as well as allowing junked packets to be logged. An ignored packet would be signalled by pre-cancelling the event.

2023-02-08 10:08 UTC, dktapps commented on src/event/server/DataPacketPreReceiveEvent.php
> +
I don't see the point of these constants.

2023-02-08 10:08 UTC, dktapps commented on src/event/server/DataPacketPreReceiveEvent.php
> +	];
This shouldn't be defined here. If we decide to start using these packets in the future, this is going to be a surprising footgun for anyone who wants to use them.

2023-02-08 12:54 UTC, aderoian commented on src/event/server/DataPacketPreReceiveEvent.php
> +	];
I agree, however, I feel that there should be a list of the "junk" packets somewhere. A lot of those are marked as todo and can be removed, yes.

2023-02-19 05:04 UTC, aderoian commented
I am not sure if that if statement is the best place to check for certain packets, but it's much better than the original event. Additionally, this change possibly should be in ``next-major`` as any plugin depending on one of these packets will be affected.

2023-03-04 17:24 UTC, dktapps commented
To me, it seems that deciding to blacklist some packets is not really relevant to the original intent here, which is to simply add a DataPacketPreReceiveEvent. Where and how to blacklist packets is a problem that can be discussed separately.

2023-03-05 05:36 UTC, aderoian commented
Just to be certain, we only want to be calling the event, no pre-canceling of the event?

2023-03-05 16:07 UTC, dktapps commented
for now yes

2023-03-06 18:00 UTC, dktapps commented on src/event/server/DataPacketPreReceiveEvent.php
> +class DataPacketPreReceiveEvent extends ServerEvent implements Cancellable{
Please add documentation for this.

2023-03-14 18:56 UTC, dktapps commented on src/network/mcpe/NetworkSession.php
> +
The event call should be covered by receiveDataPacket timings.

2023-03-15 15:13 UTC, dktapps commented on src/event/server/DataPacketPreReceiveEvent.php
> +	}
Formatting issue here (remove the extra newline)

2023-03-15 15:13 UTC, dktapps commented on src/network/mcpe/NetworkSession.php
> +			$timings->stopTiming();
You can put the event call inside the `try` and avoid having this extra call (the `finally` will take care of it).

2023-03-15 22:12 UTC, dktapps commented on src/network/mcpe/NetworkSession.php
> +			$timings->startTiming();
This line can be moved outside the `try` as well

2023-03-15 22:47 UTC, merged

2023-03-16 03:54 UTC, IvanCraft623 commented
I think event's name isn't accurate, it may not be understood the concept of "PreReceive" because to understand what the event actually does you have to read the documentation, it would make more sense "PreDecode".

2023-03-16 11:40 UTC, dktapps commented
To be honest I'd like to rename DataPacketReceiveEvent to DataPacketHandleEvent, and have this be DataPacketReceiveEvent instead. But that would cause a confusing mess for plugins.