Implement MoveActorDeltaPacket
pmmp/PocketMine-MP pull request #5574
Opened 2023-02-14 22:48 UTC by AkmalFairuz

## Introduction
Implement MoveActorDeltaPacket

### Relevant issues
Fix https://github.com/pmmp/PocketMine-MP/issues/5568

## Changes
### API changes

### Behavioural changes

## Backwards compatibility

## Follow-up

## Tests

2023-02-14 22:51 UTC, dktapps requested changes
The position used in sendSpawnPacket needs to be changed to use the last broadcast position as well, or the initial delta may accumulate errors.

2023-02-14 22:51 UTC, dktapps commented on src/entity/Entity.php
> +		$this->lastBroadcastedMovement = Location::fromObject($offsetPosition, null, $this->location->yaw, $this->location->pitch);
We already have `lastLocation` for this.

2023-02-15 12:06 UTC, dktapps commented on src/entity/Entity.php
> +			$this->lastLocation->asVector3(),
This needs to be changed in subclasses as well.

2023-02-15 12:07 UTC, dktapps commented
It occurs to me that it may not be possible to ensure that plugin devs use the correct position in custom sendSpawnPacket implementations. If an incorrect position is used, the delta position will accumulate errors and the source of the problem will be far from obvious.

Any suggestions how to combat this?

2023-02-15 12:15 UTC, dktapps requested changes

2023-02-15 12:15 UTC, dktapps commented on src/entity/Entity.php
> +			$deltaLoc = $offsetPosition->subtractVector($this->getOffsetPosition($this->lastLocation));
This calculation is useless. With the current code, you can directly compare lastLocation->whatever with currentLocation->whatever.

2023-02-15 12:15 UTC, dktapps commented on src/entity/Entity.php
> +			if(($this->location->pitch - $this->lastLocation->pitch) !== 0.0){
This subtraction is pointless. It's not telling you anything that an equality operator wouldn't.

2023-02-15 12:15 UTC, dktapps commented on src/entity/Entity.php
> +			if(($this->location->yaw - $this->lastLocation->yaw) !== 0.0){
Same here.

2023-02-15 15:24 UTC, dktapps commented on src/entity/Entity.php
>  			$this->location->yaw,
These also need to use `lastLocation`.

2023-02-17 16:41 UTC, AkmalFairuz commented
> It occurs to me that it may not be possible to ensure that plugin devs use the correct position in custom sendSpawnPacket implementations. If an incorrect position is used, the delta position will accumulate errors and the source of the problem will be far from obvious.
> 
> Any suggestions how to combat this?

Store players who need an absolute move packet when spawned to players, then send absolute move packet when movement packet is broadcasted. See my commit

2023-02-17 16:51 UTC, dktapps commented
You could probably reduce it to a boolean flag. Not much sense in adding the extra memory usage and complexity. It anyway might be useful to send periodic absolute updates anyway.

2023-03-04 17:22 UTC, dktapps commented
I meant a single boolean, not an array of booleans.

2023-03-14 18:54 UTC, dktapps commented on src/entity/Entity.php
> +	protected $needsAbsoluteMovement = true;
Use native types for this. Also, this should be `private`.

2023-03-14 18:54 UTC, dktapps commented on src/entity/Entity.php
>  				$this->spawnTo($player);
This is no longer going to work correctly, since it's now using the lastLocation.

2024-11-13 18:56 UTC, closed without merging