Caching creative inventory entries
pmmp/PocketMine-MP pull request #5703
Opened 2023-04-16 09:50 UTC by ShockedPlot7560

## Introduction

I could notice during a debugging that the entries of the packet that is sent to the client to synchronize the creative menu, was recalculated each time.  

This is quite surprising because it is not linked to the player and therefore can only change if you add/remove items from the creative menu.

This difference is much bigger with an important number of items more than pocketmine base. 950 base items against 1700 for my case.

Implementing this caching system allows to reduce the sending of the creative inventory to just what is necessary: the encoding / network compression.

## Changes
### API changes

* Added ``CreativeInventoryCache``

## Tests

* Launch server
* Active timings
* Connect player
* I did my test by alternating a change of game mode from survival to creative, creative survival, 4 times (4 commands)
* Recover your timings

You should not see a significant difference with the basic pocketmine data.

2023-04-16 12:28 UTC, dktapps commented
Seems to me like we need TypeConverter timings.

2023-04-16 13:18 UTC, ShockedPlot7560 commented
It is that with or without, the systematic calculation is not necessary.

Do you mean that I have to add the timings in the pull request, or that I have to provide other things?

2023-04-16 13:21 UTC, dktapps commented
No, you don't need to worry about that. It's just an afterthought I had when looking at the PR.

I'm not a huge fan of caching the entries this way since it'll add to the server idle memory footprint. I know we already do the same thing for crafting, but I'm not a fan of it there either.

Perhaps it warrants some investigation into why this is so slow.

2023-04-16 13:30 UTC, ShockedPlot7560 commented
I'm not a big fan either, but considering what the server does for this, the problem is not the conversion of items. But it comes rather from the numerous iterations to do, one for all the items to clone them and another one that comes to convert them.

2023-04-18 11:29 UTC, dktapps commented
> I'm not a big fan either, but considering what the server does for this, the problem is not the conversion of items. But it comes rather from the numerous iterations to do, one for all the items to clone them and another one that comes to convert them.

I hadn't considered that cloning items in getAll() might have performance implications for this. I don't suppose you've measured the impact of this?

From what I recall, the main issue with cloning items is that their NBT trees have to be recursively cloned, which is quite costly.

2023-04-18 13:11 UTC, ShockedPlot7560 commented
I didn't measure the impact, but getting the list of creative items requires a recursive clone of all the items

2023-04-18 13:16 UTC, ShockedPlot7560 commented
But I can try to measure the impact from my side and give the results here. know where the problem really comes from

2023-04-18 13:33 UTC, dktapps commented
I've just done a test run, the majority of the overhead actually comes from Item::serializeCompoundTag(). We might be able to optimise this somewhat, but it's not likely it will improve much.

2023-04-18 13:51 UTC, ShockedPlot7560 commented
It is always possible to optimize on the creative side but this masks another problem which is the serialization

2023-04-26 22:58 UTC, dktapps requested changes
I think this should be done in a similar manner to `CraftingDataCache`. It's not guaranteed that there will only be a singular `CreativeInventory` instance (see #5694), nor that the cache will live forever.

2023-04-26 22:58 UTC, dktapps commented on src/inventory/CreativeInventoryCache.php
> +	private bool $isHit = false;
You can do this by making `$entries` nullable instead of having an extra field.

2023-04-26 22:58 UTC, dktapps commented
Concept ACK on this. We're already doing the same thing for crafting, so I don't think it's a problem to add a cache for this as well (the footprint should be microscopic in comparison).

2023-04-29 16:16 UTC, ShockedPlot7560 commented
I just modified the system to support multiple instances of the creative inventory

2023-05-08 16:20 UTC, dktapps requested changes

2023-05-08 16:20 UTC, dktapps commented on src/inventory/cache/CreativeInventoryCache.php
> +namespace pocketmine\inventory\cache;
This class belongs in `pocketmine\network\mcpe\cache`

2023-05-08 16:20 UTC, dktapps commented on src/inventory/cache/CreativeInventoryCache.php
> +	public function getCache(CreativeInventory $inventory) : CreativeContentPacket {
```suggestion
	public function getCache(CreativeInventory $inventory) : CreativeContentPacket{
```

2023-05-08 16:20 UTC, dktapps commented on src/inventory/CreativeInventory.php
> +	private function onContentChange() : void {
```suggestion
	private function onContentChange() : void{
```

2023-05-18 13:10 UTC, dktapps approved these changes

2023-05-18 13:11 UTC, merged