PlayerDeathEvent add setScreenDeathMessage()
pmmp/PocketMine-MP pull request #5726
Opened 2023-04-29 11:43 UTC by BrandPVP

## Introduction

Currently its not possible to set different death messages in the chat and on the screen. Even if you try to send a new DeathInfoPacket, thats not gonna work because it can only be sent once.

Or if you want to hide the chat message and show only the screen message.
You can't just do setDeathMessage("""), because it will be sent in a DeathInfoPacket and you will not be able to send a new one.

### Relevant issues

## Changes
### API changes

### Behavioural changes

## Backwards compatibility

## Follow-up

## Tests

2023-05-07 19:15 UTC, andriycraft approved these changes

2023-05-19 13:45 UTC, dktapps requested changes
The idea is OK, but the naming of some of this stuff is questionable

2023-05-19 13:45 UTC, dktapps commented on src/event/player/PlayerDeathEvent.php
> +	public function getScreenDeathMessage() : Translatable|string{
I think `getDeathScreenMessage()` would be more idiomatic.

2023-05-19 15:17 UTC, dktapps approved these changes
I think this change also calls for documentation of the difference between the methods, but that can be done later.

2023-05-19 15:18 UTC, merged