Add of new minecraft colours, deletion of colours that have been removed from the game
pmmp/PocketMine-MP pull request #5775
Opened 2023-05-29 17:39 UTC by roimee6

## Introduction
Minecraft has just added the colours that are linked to the materials (colours slightly modified from the classic ones) and Minecraft has removed a few other colours (I don't know since when) which are the underline and the strikethrough. 

## Tests
On this photo I realised that minecraft didn't have the underline and the strikethrough (I removed them).
![image](https://github.com/pmmp/PocketMine-MP/assets/40174895/f9832b69-85b3-4adf-a86c-5d41489e140c)

2023-05-29 20:21 UTC, dktapps requested changes
Again, please do **not** use the GitHub Web Editor or use it to upload files. Install git from https://git-scm.com and use it to commit your changes.

2023-05-29 20:21 UTC, dktapps commented on src/utils/Terminal.php
> -	public static string $FORMAT_STRIKETHROUGH = "";
This is BC breaking and requires a major version.

2023-05-29 20:21 UTC, dktapps commented on src/utils/Terminal.php
> -	public static string $FORMAT_STRIKETHROUGH = "";
In addition, consoles may have a way to represent these codes, regardless of whether they are supported by Minecraft.

2023-05-29 20:21 UTC, dktapps commented on src/utils/Terminal.php
> +        self::$COLOR_MATERIAL_AMETHYST = $color(171);
What's your source for these colour codes?

2023-05-29 20:21 UTC, dktapps commented on src/utils/Terminal.php
> +			self::$COLOR_MATERIAL_REDSTONE = $setaf(9);
`9` may mean different things in 16-color vs 256-color. This isn't reliable.

2023-05-29 20:21 UTC, dktapps commented on src/utils/Terminal.php
> +			self::$COLOR_MATERIAL_LAPIS = $setaf(12);
As above.

2023-05-29 20:21 UTC, dktapps commented on src/utils/Terminal.php
> +                TextFormat::MATERIAL_IRON => seTerminallf::$COLOR_MATERIAL_IRON,
I have no idea what's going on here, but it needs to be fixed.

2023-05-29 20:21 UTC, dktapps commented on src/utils/Terminal.php
> +}
Useless EOF change

2023-05-29 20:21 UTC, dktapps commented on src/utils/TextFormat.php
> -	public const UNDERLINE = TextFormat::ESCAPE . "n";
These can't be removed (BC breaking).

2023-05-29 20:21 UTC, dktapps commented on src/utils/TextFormat.php
> +				case TextFormat::MINECOIN_GOLD :
Formatting issue here.

2023-05-29 20:21 UTC, dktapps commented on src/utils/TextFormat.php
> +					$newString .= "<span style=color:#9a5cc5>";
Source for these hex codes?

2023-05-29 20:21 UTC, dktapps commented on src/utils/TextFormat.php
> +}
Useless EOF change

2023-06-11 12:55 UTC, dktapps commented
Bump. Are you planning to complete this PR?

2023-06-15 20:04 UTC, closed without merging

2023-06-15 20:07 UTC, roimee6 commented
New pr

2023-06-19 11:08 UTC, dktapps commented
You didn't have to do that... it's entirely possible to modify an existing PR