Introduce planks type
pmmp/PocketMine-MP pull request #5895
Opened 2023-07-13 20:35 UTC by ShockedPlot7560

## Introduction
With Mojang's introduction of mosaic bamboo, it's necessary to have a way of distinguishing it.  
This is a somewhat direct way of dividing the blocks inheriting the planks from those inheriting the wood, but it is the most flexible way of making it easier to introduce mosaic bamboo blocks.

This PR goes hand in hand with #5875, which seems to need this API.

## Changes
### API changes
- Added ``PlanksType``, it inserts ``WoodType`` values as standard, but may be extended in the future.
- Remove ``getWoodType`` for using ``getPlanksType`` in ``Planks``, ``WoodenSlab`` and ``WoodenStairs``
- Added ``PlanksLikeBlockIdHelper`` 
- Rename ``WoodType`` to ``LogType``
- Rename ``WoodTypeTrait`` to ``LogTypeTrait``
- Change ``writeLegacyWoodType`` to ``writeLegacyLogType`` in ``BlockStateWriter``
- Rename ``getWoodType`` to ``getLogType`` in ``BoatType``

## Backwards compatibility
- Api changed in `Planks`, `WoodenSlab` and `WoodenStairs`
- ``WoodType`` renamed in ``LogType``
- ``WoodTypeTrait`` renamed in ``LogTypeTrait``
- Change ``writeLegacyWoodType`` to ``writeLegacyLogType`` in ``BlockStateWriter``

## Follow-up
- Implements Bamboo Mosaic

2023-07-13 21:19 UTC, dktapps commented
WoodType should probably be scrapped and replaced with LogType

2023-07-18 11:35 UTC, dktapps requested changes
I think there is some confusion here over what's appropriate to use for the different types of blocks.

2023-07-18 11:35 UTC, dktapps commented on src/block/BaseSign.php
> +	public function __construct(BlockIdentifier $idInfo, string $name, BlockTypeInfo $typeInfo, LogType $logType, \Closure $asItemCallback){
This doesn't seem right... there are bamboo signs

2023-07-18 11:35 UTC, dktapps commented on src/block/FenceGate.php
> +	use LogTypeTrait;
Same again here

2023-07-18 11:35 UTC, dktapps commented on src/block/PlanksLikeBlockIdHelper.php
> +}
I'm not really sure what's gained by pulling this out into its own class.

2023-07-18 11:35 UTC, dktapps commented on src/block/WoodenDoor.php
> +	use LogTypeTrait;
Bamboo door is a thing

2023-07-18 11:35 UTC, dktapps commented on src/block/WoodenFence.php
> +	use LogTypeTrait;
and bamboo fence

2023-07-18 11:35 UTC, dktapps commented on src/block/WoodenPressurePlate.php
> +	use LogTypeTrait;
and pressure plate

2023-07-18 11:35 UTC, dktapps commented on src/block/WoodenTrapdoor.php
> +	use LogTypeTrait;
and trapdoor

2023-07-18 11:35 UTC, dktapps commented on src/block/utils/PlanksType.php
> +			...self::fromLogType()
This is generally not recommended

2023-07-18 11:35 UTC, dktapps commented on src/item/BoatType.php
> +			new self("mangrove", LogType::MANGROVE()),
boats are made from planks

2023-10-18 09:41 UTC, dktapps commented on src/block/utils/LogTypeTrait.php
> +trait LogTypeTrait{
Seems like this trait is now redundant, as far as I can see

2023-10-18 09:41 UTC, dktapps commented on src/block/utils/PlanksType.php
> +		foreach(LogType::getAll() as $type) {
This is probably not a good idea - it won't translate well to native enums

2023-10-18 09:44 UTC, dktapps commented
I feel like `PlanksType` should remain as `WoodType`. `LogType` is the outlier here, since it only applies to one block type. This would minimize unnecessary API breaks and reduce the diff size.

2023-10-20 21:32 UTC, ShockedPlot7560 commented
> I feel like `PlanksType` should remain as `WoodType`. `LogType` is the outlier here, since it only applies to one block type. This would minimize unnecessary API breaks and reduce the diff size.

However, the reason for separating is to be able to distinguish between planks and logs. The problem arises with bamboo and bamboo planks.

2023-10-21 07:21 UTC, dktapps commented
Bamboo is still a wood type, it just doesn't have an associated log type.

As I said, I don't think the BC break of renaming all of this stuff to `Planks` is justified. Only logs really need to change IMO.

2024-11-24 12:44 UTC, dktapps commented
Closing this due to lack of activity and conflicts. Introducing a `LogType` would be a lot simpler and require less work.

2024-11-24 12:44 UTC, closed without merging