Implement Smithing Templates
pmmp/PocketMine-MP pull request #6132
Opened 2023-11-02 17:24 UTC by pandaa-be

## Introduction
This PR will add all Smithing Templates for a comming Armor Trim PR

## Changes
### API changes
Some new Items in VanillaItems

2023-11-03 15:29 UTC, pandaa-be commented
Why is "CI / Generated Code consistency checks" failed?

2023-11-03 15:32 UTC, jasonw4331 commented
It failed because you didn't autogenerate the phpdocs like the instructions say to

2023-11-03 15:35 UTC, jasonw4331 requested changes
VanillaItems doc comments must be autogenerated using the build scripts instead of being done by hand.

2023-11-03 15:53 UTC, pandaa-be commented
> VanillaItems doc comments must be autogenerated using the build scripts instead of being done by hand.

![image](https://github.com/pmmp/PocketMine-MP/assets/135014092/ad7a279e-9adb-49f1-bb17-1e4ee64373f7)...

2023-11-03 16:17 UTC, pandaa-be commented
Nvm I think i uploaded the wrong file

2023-11-06 16:05 UTC, dktapps commented on src/item/VanillaItems.php
> +		self::register("netherite_upgrade_smithing_template", new Item(new ItemIdentifier(ItemTypeIds::NETHERITE_UPGRADE_SMITHING_TEMPLATE), "Smithing Template"));
`
```suggestion
		self::register("netherite_upgrade_smithing_template", new Item(new IID(Ids::NETHERITE_UPGRADE_SMITHING_TEMPLATE), "Smithing Template"));
```
The imports are aliased for readability

2023-11-06 16:05 UTC, dktapps commented on src/item/VanillaItems.php
> +		self::register("netherite_upgrade_smithing_template", new Item(new ItemIdentifier(ItemTypeIds::NETHERITE_UPGRADE_SMITHING_TEMPLATE), "Smithing Template"));
Also, why is this just called "smithing template"? Shouldn't it have a more specific name?

2023-11-09 14:25 UTC, merged