Implement Border
pmmp/PocketMine-MP pull request #6146
Opened 2023-11-09 07:08 UTC by pandaa-be

## Introduction
Implement (Border)[https://minecraft.wiki/w/Border] Block

## Changes
### API changes
`VanillaBlocks::BORDER()`

2023-11-09 12:26 UTC, pandaa-be commented
Nah I think PHPUnit has some errors, not my code ;(

2023-11-09 14:18 UTC, dktapps commented
> Nah I think PHPUnit has some errors, not my code ;(

You need to run the script `tests/phpunit/block/regenerate_consistency_check.php`. It'll update a JSON file in the tests folder which should be committed.

2023-11-09 14:19 UTC, dktapps commented on src/block/Border.php
> +}
Why does this have its own class if you're not going to add any functionality to it?

2023-11-09 14:19 UTC, dktapps requested changes
This does not implement any of the border block's useful logic (preventing entities from passing above or below) and as such is entirely dependent on the client to respect this.

2023-11-09 14:29 UTC, pandaa-be commented
> This does not implement any of the border block's useful logic (preventing entities from passing above or below) and as such is entirely dependent on the client to respect this.

Isn't it enough if the border is already client-side or do you mean that server-side mobs can get through?

2023-11-09 14:34 UTC, dktapps commented
No, it's not enough.

2023-11-09 14:41 UTC, alvin0319 commented
Relying on the client-side means the malicious client could bypass it.

2023-11-09 14:42 UTC, pandaa-be commented
ok ok my mistake, I'll correct it

2023-11-09 14:44 UTC, pandaa-be commented
I thinked it would be okay if it is just client-side because of this:
https://discordapp.com/channels/373199722573201408/373199722573201410/1171872447327371386

2023-11-09 14:50 UTC, JavierLeon9966 commented
> Relying on the client-side means the malicious client could bypass it.

In that case `setNoClientPredictions()` should verify server side immobility but that's outside the scope of this PR.

2023-11-09 14:51 UTC, JavierLeon9966 commented
> ok ok my mistake, I'll correct it

Remember some entities can cross the border block: https://minecraft.wiki/w/Border

2023-11-09 14:52 UTC, JavierLeon9966 commented
> I thinked it would be okay if it is just client-side because of this: https://discordapp.com/channels/373199722573201408/373199722573201410/1171872447327371386

I thought client side was enough. Just do what Dylan says.

2023-11-09 14:55 UTC, pandaaaBE commented
> > I thinked it would be okay if it is just client-side because of this: https://discordapp.com/channels/373199722573201408/373199722573201410/1171872447327371386
> 
> I thought client side was enough. Just do what Dylan says.

But first I have to find out how I can stop the movements server-side without using barrier blocks, how this is supposed to work is currently a mystery to me

2023-11-09 15:02 UTC, pandaa-be commented
**Ok honestly I don't understand how this is supposed to work server-side, if someone wants to continue the PR then I won't stop them.**

2023-11-09 15:14 UTC, pandaa-be commented
Notitz: Client-side it is really useless, when rejoining it is as if the border had never existed...

2023-11-09 15:22 UTC, JavierLeon9966 commented
> Notitz: Client-side it is really useless, when rejoining it is as if the border had never existed...

Yeah, you need to do something special with the LevelChunkPacket encoding.

2023-11-14 12:05 UTC, closed without merging

2024-02-04 11:13 UTC, pandaa-be commented
@dktapps how would you implement this block?