Implement Shield
pmmp/PocketMine-MP pull request #6296
Opened 2024-03-22 12:48 UTC by pandaa-be

## Introduction
This PR adds working shield.

## Changes
### API changes
`VanillaItems::SHIELD()`

## Tests

I tested this PR by doing the following (tick all that apply):
- [ ] Writing PHPUnit tests (commit these in the `tests/phpunit` folder)
- [ ] Playtesting using a Minecraft client (provide screenshots or a video)
- [ ] Writing a test plugin (provide the code and sample output)
- [ ] Other (provide details)

2024-03-26 20:23 UTC, JavierLeon9966 requested changes
Instead of naming the methods and properties `breakShield` it should be like "shield disabled". `canDisableShield`, `isShieldDisabled`, `getShieldDisableCooldown`, etc.

2024-03-26 20:23 UTC, JavierLeon9966 commented on src/entity/Human.php
> +		$shieldOffhand = $this->getOffhandInventory()->getItem(0);
```suggestion
		$shieldOffhand = $this->getOffHandInventory()->getItem(0);
```

2024-03-26 20:23 UTC, JavierLeon9966 commented on src/entity/Living.php
> +
```suggestion
```

2024-03-26 20:23 UTC, JavierLeon9966 commented on src/entity/Living.php
> +			$damager->isAttackTimeByShieldKb = true;
Why do we need to reset the damager's invincibility ticks and flag if it was by shield? This doesn't seem necessary

2024-03-26 20:23 UTC, JavierLeon9966 commented on src/entity/Living.php
> +	public function preAttack(Player $player) : void{
This is unused. What is this for?

2024-03-26 20:23 UTC, JavierLeon9966 commented on src/entity/Living.php
> +	public function postAttack(Player $player) : void{
Same for this.

2024-03-26 20:23 UTC, JavierLeon9966 commented on src/event/entity/EntityDamageBlockedEvent.php
> +class EntityDamageBlockedEvent extends EntityDamageByEntityEvent{
This class seems useless when you can just do:
```php
$ev = new EntityDamageByEntityEvent($damager, $entity, EntityDamageEvent::CAUSE_BLOCKING, $damage);
```

2024-03-26 20:23 UTC, JavierLeon9966 commented on src/item/Shield.php
> +	public function getCooldownTicks() : int{
Shields have no interaction cooldown.

2024-03-26 20:23 UTC, JavierLeon9966 commented on src/player/Player.php
> +			$this->resetItemCooldown($this->getOffHandInventory()->getItem(0));
The cooldown is supposed to be for blocking, not interacting.

2024-07-05 09:20 UTC, closed without merging

2024-07-05 09:21 UTC, pandaa-be commented
Closed because the current code is probably not good enough