Update world protocol version
pmmp/PocketMine-MP pull request #6399
Opened 2024-07-11 16:25 UTC by Gaprix

2024-07-12 09:54 UTC, dries-c commented
I'm not sure if this makes sense given the bedrock data hasn't changed at all

2024-07-12 12:23 UTC, dktapps requested changes

2024-07-12 12:23 UTC, dktapps commented on src/data/bedrock/block/BlockStateData.php
> +		(2); //revision
This is only supposed to change if the block palette was updated (and a new blockstate upgrade schema added)

2024-07-12 12:25 UTC, Gaprix commented on src/data/bedrock/block/BlockStateData.php
> +		(2); //revision
But at the same time, PocketMine will not be able to open the vanilla world 1.21.2 without this change

2024-07-12 12:26 UTC, Gaprix commented on src/data/bedrock/block/BlockStateData.php
> +		(2); //revision
Or do you mean a change specifically in this class?

2024-07-12 12:27 UTC, dktapps commented on src/data/bedrock/block/BlockStateData.php
> +		(2); //revision
This specific change is invalid

2024-07-14 18:16 UTC, dktapps approved these changes

2024-07-16 05:48 UTC, IvanCraft623 approved these changes

2024-07-16 05:51 UTC, merged