EnderPearls now teleports to the correct world
pmmp/PocketMine-MP pull request #6450
Opened 2024-09-10 17:37 UTC by dadodasyra

## Introduction
EnderPearls currently teleports the player where it landed in the player world when the projectile hit something.
Normal behaviour should be that player is teleported to the coordinates AND the world **of the ender pearl**.

## Changes
### API changes
None

### Behavioural changes
None except what's written in introduction.

## Backwards compatibility
Should not be a thing.

## Follow-up
This may be completed by a system to avoid teleporting player after it's death.

I tested this PR by doing the following (tick all that apply):
- [ ] Writing PHPUnit tests (commit these in the `tests/phpunit` folder)
- [ ] Playtesting using a Minecraft client (provide screenshots or a video)
- [ ] Writing a test plugin (provide the code and sample output)
- [x] Other (This was written in PhpStorm, no syntax issues, CIs runs well and there's no reason that it broke something.)

2024-09-11 15:08 UTC, dktapps commented
I think it would make more sense to not teleport the player if they are in a different world. Can't really think of a reason why anyone would want to be teleported back to the world they just left.

2024-09-11 15:10 UTC, dktapps commented
Really this ought to be locked behind a teleport counter and is generally a bigger problem than multiworld. See https://github.com/pmmp/PocketMine-MP/issues/3397#issuecomment-624227904

2024-09-11 15:11 UTC, dktapps requested changes
New behaviour doesn't make much sense. See comments on https://github.com/pmmp/PocketMine-MP/issues/3397#issuecomment-624227904 and related issues.

2024-09-11 21:36 UTC, dadodasyra commented
After some singleplayer vanilla testing it seems that : 
- The ender pearl teleport is cancelled between dimensions
- Death doesn't change anything to the current thrown ender pearls. If the player dies and respawn fast enough he's still teleported.

Will take a look at it when I have the time. For the time I move to a draft

2024-09-12 12:40 UTC, dktapps commented
What vanilla does is irrelevant. The expected behaviour should be the behaviour that makes the most sense.

2024-11-10 15:48 UTC, dktapps commented
Closing due to inactivity

2024-11-10 15:48 UTC, closed without merging