Add dynamic build date using time() function in VersionInfo
pmmp/PocketMine-MP pull request #6473
Opened 2024-10-25 10:16 UTC by AzaleeX

This update introduces a dynamic build date in the `VersionInfo` class using the `time()` function, allowing the build date to be set at runtime. This change ensures that the build date is always current without needing manual updates.

- remove from Todos list

2024-10-25 12:54 UTC, jasonw4331 commented
The server isn't built during runtime. It's built during build time...

2024-10-25 12:59 UTC, dktapps requested changes

2024-10-25 12:59 UTC, dktapps commented on src/VersionInfo.php
> +		return time();
It's supposed to be the time the phar was built, not the time the function was called.
This isn't as simple as just adding an extra function.

2024-11-02 11:09 UTC, dktapps commented on src/VersionInfo.php
> +				if (isset($meta["date"])) {
This isn't going to magically appear in the phar metadata

2024-11-29 14:43 UTC, dktapps commented
Closing due to lack of activity on review comments and little need for this change anyway

2024-11-29 14:43 UTC, closed without merging