Add Bamboo Block Mappings
pmmp/PocketMine-MP pull request #6474
Opened 2024-10-25 12:56 UTC by AzaleeX

## Introduction
Added mappings for Bamboo blocks, including Bamboo Door and Bamboo Sign, to the ItemSerializerDeserializerRegistrar.

> [!WARNING]
> I'm not sure it's legal to put IDSs directly in functions such as getLogIdentifier() or getAllSidedLogIdentifier() because banboo has nothing similar and has no log.

## Tests

I tested this PR by doing the following (tick all that apply):
- [ ] Writing PHPUnit tests (commit these in the `tests/phpunit` folder)
- [ ] Playtesting using a Minecraft client (provide screenshots or a video)
- [ ] Writing a test plugin (provide the code and sample output)
- [ ] Other (provide details)

2024-10-25 13:09 UTC, dktapps requested changes
I think the reason we didn't already add these was because of the issue around logs, but this is not the right way to fix it.

2024-10-25 13:09 UTC, dktapps commented on src/block/WoodLikeBlockIdHelper.php
> +	 */
Unrelated change

2024-10-25 13:09 UTC, dktapps commented on src/block/WoodLikeBlockIdHelper.php
> +			WoodType::BAMBOO => 59000,
No

2024-10-25 13:09 UTC, dktapps commented on src/block/WoodLikeBlockIdHelper.php
> +			WoodType::BAMBOO => 59001,
Also no

2024-10-25 13:09 UTC, dktapps commented on src/data/bedrock/item/ItemSerializerDeserializerRegistrar.php
> +		$this->map1to1Block(Ids::BAMBOO_DOOR, Blocks::BAMBOO_DOOR());
This list is supposed to be in alphabetical order

2024-10-25 13:09 UTC, dktapps commented on src/data/bedrock/item/ItemSerializerDeserializerRegistrar.php
> +		$this->map1to1Item(Ids::BAMBOO_SIGN, Items::BAMBOO_SIGN());
Same again here

2024-10-25 13:09 UTC, dktapps commented on src/item/StringToItemParser.php
>  		$result->registerBlock("bamboo_sapling", fn() => Blocks::BAMBOO_SAPLING());
Alphabetical order

2024-10-25 13:09 UTC, dktapps commented on src/item/VanillaItems.php
> +		self::register("bamboo_sign", new ItemBlockWallOrFloor(new IID(Ids::BAMBOO_SIGN), Blocks::BAMBOO_SIGN(), Blocks::BAMBOO_WALL_SIGN()));
Alphabetical order

2024-10-25 13:09 UTC, dktapps commented on src/item/VanillaItems.php
> + * @method static ItemBlockWallOrFloor BAMBOO_SIGN()
This docblock is supposed to be generated by a script, not hand-edited

2024-10-25 13:18 UTC, AzaleeX commented on src/block/WoodLikeBlockIdHelper.php
> +			WoodType::BAMBOO => 59000,
What should I do?

2024-10-25 13:18 UTC, AzaleeX commented on src/block/WoodLikeBlockIdHelper.php
> +			WoodType::BAMBOO => 59001,
What should I do?

2024-10-25 13:33 UTC, nicholass003 commented on src/block/WoodLikeBlockIdHelper.php
> +			WoodType::BAMBOO => 59000,
You have to update or create new ids here
https://github.com/pmmp/PocketMine-MP/blob/stable/src/block/BlockTypeIds.php

2024-10-25 13:34 UTC, nicholass003 commented on src/block/WoodLikeBlockIdHelper.php
> +			WoodType::BAMBOO => 59000,
Example :
https://github.com/pmmp/PocketMine-MP/pull/6391/files#diff-b7d3ed653a6892f8d17adae002eb6840e0d6ab5fba40e9a7afce040bd3ea5094

2024-10-26 13:15 UTC, ClousCloud commented on src/block/WoodLikeBlockIdHelper.php
> +			WoodType::BAMBOO => 59001,
You have to add the id to the src/block/BlockTypeIds.php file

2024-10-27 12:20 UTC, KnosTx commented on src/item/VanillaItems.php
> + * @method static ItemBlockWallOrFloor BAMBOO_SIGN()
Yeah, he should run the `composer update-codegen` command

2024-10-27 17:25 UTC, dktapps commented on src/block/WoodLikeBlockIdHelper.php
> +			WoodType::BAMBOO => 59001,
There is no bamboo log or "wood", but this isn't the way to fix it

2024-10-28 09:12 UTC, AzaleeX commented on src/block/WoodLikeBlockIdHelper.php
> +			WoodType::BAMBOO => 59001,
So we're just going to create an id with an existing block?

2024-10-29 07:06 UTC, ShockedPlot7560 commented
Same problem as #5875 we can't introduce bamboo as a wood type

2024-11-03 16:23 UTC, closed without merging