feat: add Crimson Nylium and Warped Nylium blocks
pmmp/PocketMine-MP pull request #6481
Opened 2024-11-03 18:18 UTC by AzaleeX

## Introduction
`Crimson Nylium` and `Warped Nylium` blocks added
![image](https://github.com/user-attachments/assets/82155268-372b-409e-8abf-653c3158ba25)

## Tests

I tested this PR by doing the following (tick all that apply):
- [ ] Writing PHPUnit tests (commit these in the `tests/phpunit` folder)
- [ ] Playtesting using a Minecraft client (provide screenshots or a video)
- [ ] Writing a test plugin (provide the code and sample output)
- [ ] Other (provide details)

2024-11-04 07:25 UTC, ShockedPlot7560 commented on src/block/GrassNylium.php
> +		if($lightAbove < 4 && $world->getBlockAt((int) $this->position->x, (int) $this->position->y + 1, (int) $this->position->z)->getLightFilter() >= 2){
Better to use `getSide(Facing::UP)`

2024-11-04 07:25 UTC, ShockedPlot7560 commented on src/block/NetherRoots.php
> +			$supportBlock->getTypeId() === BlockTypeIds::WARPED_NYLIUM ||
Better to create a new Nylium tag for that is think

2024-11-04 07:25 UTC, ShockedPlot7560 commented on src/block/RedMushroom.php
> +	use StaticSupportTrait;
Apply only minimal change, this is unrelated to the PR "add Crimson Nylium".

Open an other PR if you want to change that.

2024-11-04 07:25 UTC, ShockedPlot7560 commented on src/block/VanillaBlocks.php
> +		self::register("warped_nylium", new GrassNylium(new BID(Ids::WARPED_NYLIUM), "Warped Nylium", new Info(BreakInfo::pickaxe(0.4))));
Can be good to store in an variable the break info

2024-11-04 07:43 UTC, ipad54 commented on src/block/GrassNylium.php
> +class GrassNylium extends Opaque{
`Nylium` or `NetherNylium` would be better.

2024-11-04 07:44 UTC, ipad54 commented
Bonemeal logic is missing.

Also, this PR should target `minor-next` branch, not `stable`.

2024-11-04 08:28 UTC, ShockedPlot7560 commented
There is no block available for bone meal spreading, roots and fungus is missing

2024-11-04 08:50 UTC, ipad54 commented
> roots and fungus is missing

Roots are implemented. https://github.com/pmmp/PocketMine-MP/blob/stable/src/block/NetherRoots.php

2024-11-04 13:11 UTC, dktapps commented on src/data/bedrock/block/convert/BlockStateToObjectDeserializer.php
> +		$this->mapSimple(Ids::WARPED_NYLIUM, fn() => Blocks::WARPED_NYLIUM());
Alphabetical order please

2024-11-04 13:11 UTC, dktapps commented on src/data/bedrock/block/convert/BlockObjectToStateSerializer.php
> +		$this->mapSimple(Blocks::WARPED_NYLIUM(), Ids::WARPED_NYLIUM);
Same again here

2024-11-18 11:15 UTC, ShockedPlot7560 requested changes

2024-11-18 11:15 UTC, ShockedPlot7560 commented on src/world/generator/object/NetherGrass.php
> +	public static function growGrass(ChunkManager $world, Vector3 $pos, Random $random, int $count = 8, int $radius = 5) : void{
As there is no nether generator, I don't see the point of including a single function in a new class in the generator objects.

2024-11-18 11:15 UTC, ShockedPlot7560 commented on src/block/RedMushroom.php
> +	use StaticSupportTrait;
This isn't resolved, you still add the use of StaticSupportTrait

2024-11-18 11:15 UTC, ShockedPlot7560 commented on src/block/NetherNylium.php
> +			NetherGrass::growGrass($world, $this->position, new Random(mt_rand()), 8, 2);
What's the point of integrating all the logic into a specific function that's only used once?

2024-12-16 20:25 UTC, dktapps commented
Closing due to lack of activity

2024-12-16 20:25 UTC, closed without merging