Added support for infinite duration effects
pmmp/PocketMine-MP pull request #6531
Opened 2024-11-23 21:37 UTC by RemBog

# Infinite effects

> Added setInfinite and isInfinite methods to EffectInstance.
> Added infinite argument to /effect command to make effect infinite.
> Added a new KnowTranslation: “commands.effect.success.infinite”.

2024-11-23 21:45 UTC, dktapps requested changes
This is BC-breaking to any users of `EffectInstance::getDuration()`.

I can understand the desire for this in the `/effect` command, but I don't think we need alterations to the internals to achieve this. Providing `Limits::INT32_MAX` is good for nearly 5 years.

I could get onboard with adding support for passing `max` instead of a number for the effect duration, but the current change is too invasive for such little benefit IMO.

2024-11-25 13:34 UTC, ShockedPlot7560 commented
I can also see the need, but even if it means breaking the BC by changing the function's bound, wouldn't it be better to use null rather than -1?

2024-11-25 14:17 UTC, RemBog commented
To make the duration of the effect infinite, the duration must be equal to -1 in the packet, hence my decision to do this. I'll rework my pull request so that it doesn't break the BC soon. But if you have any ideas on how to avoid breaking the BC, I'd love to hear them, but I don't think setting null instead of -1 will help.

2024-11-25 14:45 UTC, dktapps commented
I don't think it's necessary to support infinite duration in `Effect` itself. As I said, the max duration allows for an effect that lasts nearly 5 years.

I would prefer just adding support for a `max` input to `/effect` command instead.

2024-11-25 15:10 UTC, RemBog commented
Too bad, I think it's not clean to use a large number when you want an effect to never stop. But have it your way. Minecraft Bedrock has added something that Java has had for years, and it's this kind of detail that makes the game experience cleaner, even if it's true that in the end it doesn't change anything in the player's gameplay.

2024-11-25 15:33 UTC, dktapps commented
It's not worth breaking backwards compatibility over.

2024-11-25 15:46 UTC, dktapps commented
Per suggestion from @SOF3 this could mostly avoid BC breaks by using `Limits::INT32_MAX` as the magic infinity value. This would avoid breaking code that checks `getDuration() > 0`.

It would still be a behavioural change, but the only code affected would likely have intended an infinite effect anyway.

However, this would require conversion to the appropriate Bedrock values on the network layer and for NBT entity storage.

2024-11-25 15:55 UTC, SenseiTarzan commented
> I can also see the need, but even if it means breaking the BC by changing the function's bound, wouldn't it be better to use null rather than -1?

There is based what mcbe use in sending packet

2024-11-25 15:55 UTC, SenseiTarzan commented
> I can also see the need, but even if it means breaking the BC by changing the function's bound, wouldn't it be better to use null rather than -1?

There is based what mcbe use in sending packet

2024-11-26 10:15 UTC, SOF3 commented
> > I can also see the need, but even if it means breaking the BC by changing the function's bound, wouldn't it be better to use null rather than -1?
> 
> There is based what mcbe use in sending packet

The protocol value does not need to be the internal runtime value.

2024-11-26 12:41 UTC, SenseiTarzan commented
> > > I can also see the need, but even if it means breaking the BC by changing the function's bound, wouldn't it be better to use null rather than -1?
> > 
> > There is based what mcbe use in sending packet
> 
> The protocol value does not need to be the internal runtime value.


You know he is a junior developer and I know him well and he wanted to do well but for the most interesting so as not to break the pmmp and that it works without changing anything so do not be  too hard on him because he wanted to do well

2025-01-08 01:59 UTC, closed without merging