Inventory rework
pmmp/PocketMine-MP pull request #6533
Opened 2024-11-24 21:47 UTC by dktapps

### Related issues & PRs

## Changes
### API changes

### Behavioural changes

## Backwards compatibility

## Follow-up

## Tests

2024-11-25 00:12 UTC, dktapps commented on src/block/inventory/window/EnchantingTableInventoryWindow.php
> +		$this->listener = \WeakReference::create($listener);
Probably need to clean this up, think I forgot about it

2024-11-25 13:26 UTC, ShockedPlot7560 commented
I have no real problem with the current implementation. It seems fine to me and is a first step towards a better inventory system.

Another follow-up I would suggest concerns the viewers of the inventory. I can see the point of including viewers in this system but I still have a sticking point because we're including a reference to the player in the inventory interface. Wouldn't it be good after this to think of a system where we have classes that only contain storage logic / listeners and that's it ?   
This may also be a bad idea, potentially making the code into spaghetti for inventories.

2024-11-25 14:42 UTC, dktapps commented
> I have no real problem with the current implementation. It seems fine to me and is a first step towards a better inventory system.
> 
> Another follow-up I would suggest concerns the viewers of the inventory. I can see the point of including viewers in this system but I still have a sticking point because we're including a reference to the player in the inventory interface. Wouldn't it be good after this to think of a system where we have classes that only contain storage logic / listeners and that's it ? This may also be a bad idea, potentially making the code into spaghetti for inventories.

Yeah, that's the ideal world. Unfortunately we need the Inventory to still track the viewers so that plugins can see all the viewers of an inventory, and also so that the inventory menus get closed when a block is deleted. I don't see another obvious solution to this problem. We could pull the viewer list out of `Inventory` and have the container itself manage it, but I'm not sure if that would improve anything.

2024-11-26 11:44 UTC, dktapps commented
Few issues remain with the PR:

- `BlockInventoryWindow` subclasses have minimum 3 constructor parameters - annoying for plugins, lots of room to break things - I'm thinking something like `$chest->openTo(Player $player)` would be a good idea to simplify the usage
- I haven't figured out a solution for stuff like `Furnace` which uses an `InventoryListener` to send itself a scheduled block update on a position. That's a remaining blocker for #6147.
- Possibly could use `Block` in `BlockInventoryWindow` - this is fine now that the windows aren't referenced by holders anymore, we don't need to worry about cyclic references
- No inventory type info in windows for single chest, shulker, barrel & ender chest - this isn't needed for internal use but would probably be desired by plugins; could just let them check the block type but I don't know if this should be bound to blocks

2024-12-07 14:01 UTC, dktapps commented
Double chests have also proven to be a pain in the ass and will likely be an obstacle for #6147 as well

2024-12-08 16:39 UTC, dktapps commented
Only remaining major issue is around the lengthened usage for opening inventory windows to players.

I didn't quite decide how to deal with it. There are a few things to consider:
- Not all blocks which open windows have inventories of their own (e.g. anvils, shulker boxes, crafting tables, etc.)
- Blocks which _do_ have inventories of their own may not have those inventories present (e.g. due to missing tiles) and so a mode of allowed failure would need to be introduced (e.g. `Chest->openTo()` would need to be allowed to fail). This sucks, since it will _not_ fail in 99.9% of cases (only those special cases where something hasn't been done correct by a plugin, or old worlds).
- Blocks which have inventories also usually have a feature to test for container lock. The player must use an item with a matching custom name to open such containers. Should `openTo()` check this kind of logic? If not, how do we avoid duplicated logic fetching tile in `onInteract()` vs `openTo()`? (Side note: I suppose plugins already need this boilerplate duplicated logic on stable branches, since we don't offer a simple way to get the inventory anyway.)

2025-02-10 22:06 UTC, dktapps commented
I think finishing this with nice APIs may require differentiating between "container" and "menu" blocks.
Container blocks have inventories (chest, shulkerbox, hopper, furnace, etc) while menu blocks don't (anvil, crafting table, loom, etc).

Opening a menu block should never fail since these blocks don't have inventories and cannot have locks.
Opening container blocks may fail due to incorrect item key or the tile being missing.

I also think the changes wrt. pushing inventory updates through `World` should probably be reverted also, since these aren't related to the window refactor and I'm also doubtful about the way it's been done. We'll need something like it in the future for tile de-positioning (if that's even actually possible), but for this specific PR it's not required.

2025-02-10 22:08 UTC, dktapps commented
I'm also wondering whether the player's main inventory window handling should be redone as part of this PR. We'd probably need to introduce a separate "hotbar" PlayerInventoryWindow type to facilitate this.

2025-03-24 15:17 UTC, ShockedPlot7560 requested changes

2025-03-24 15:17 UTC, ShockedPlot7560 commented on src/player/Player.php
> +		$this->logger->debug("Opening inventory " . get_class($window) . "#" . spl_object_id($window));
This can probably be changed in `Opening window` to keep the right vocabulary

2025-03-24 15:17 UTC, ShockedPlot7560 commented on src/player/Player.php
>  			$this->logger->debug("Closing inventory " . get_class($this->currentWindow) . "#" . spl_object_id($this->currentWindow));
Same here

2025-03-24 15:17 UTC, ShockedPlot7560 commented on src/player/Player.php
> +			$this->permanentWindows[spl_object_id($window)] = $window;
This can probably now create confusion ? Before, the inventory is normally the same instance while now the window could be different with the same inventory instance.

2025-03-24 15:25 UTC, dktapps commented on src/player/Player.php
> +			$this->permanentWindows[spl_object_id($window)] = $window;
No, these windows are always open, they can't be changed

2025-08-30 23:23 UTC, dktapps commented
Alright. I think I'm finally done with this

2025-09-02 18:22 UTC, dktapps commented
In the interest of avoiding branch rot I'm going to get this merged, the final result won't look too different from this anyway. Pls let me know if there are issues found after the fact.

2025-09-02 18:23 UTC, merged