Added API for resetting title duration
pmmp/PocketMine-MP pull request #844
Opened 2017-04-17 18:34 UTC by TheDiamondYT1

2017-04-17 19:18 UTC, TheDiamondYT1 commented
If you wait i will push the title command aswell.

2017-04-18 00:53 UTC, ImagicalGamer commented
Might I suggest something other than title as the command name? It has ActionBar and Subtitle, the name may be misleading to the more stupid members of the community.

2017-04-18 00:53 UTC, 0x15f approved these changes

2017-04-18 01:16 UTC, jojoe77777 commented
> Might I suggest something other than title as the command name? It has ActionBar and Subtitle, the name may be misleading to the more stupid members of the community.

@ImagicalGamer it's the same as vanilla MCPE, blame shoghi

2017-04-18 01:17 UTC, AppleDevelops commented
Don't blame it on shoghi, it's like this on MCPC too

2017-04-18 01:17 UTC, jojoe77777 commented
@AppleDevelops always blame shoghi

2017-04-18 01:32 UTC, TheDiamondYT1 commented
@jojoe77777 @AppleDevelops @ImagicalGamer I just went onto MCPE, typed /title and looked at the autocompletions.

2017-04-18 07:02 UTC, Matthww commented
Since there already is a "AddTitle" is it not better to call the subtitle: "AddSubTitle" instead of "SendSubTitle" ?

2017-04-18 09:12 UTC, dktapps commented
@Matthww Subtitles won't work by themselves. You can't "add" one without a corresponding title. That function should only be used for _changing_ the subtitle by plugins.

2017-04-18 09:14 UTC, Matthww commented
@dktapps I know. Even though it doesn't make a difference. If you already called the title feature "AddTitle" why would you call the subtitle "SendSubTitle" instead of "AddSubTitle"?

2017-04-18 09:17 UTC, dktapps commented
My question is why he has made a separate method for that at all. addTitle() with parameters should be sufficient. It doesn't make sense to add a sub by itself because it won't work.

2017-04-18 09:18 UTC, Matthww commented
@dktapps Oh I get it. Why didn't you tag him instead. I was just giving him a suggestion.

2017-04-18 09:18 UTC, dktapps commented
@Matthww I misread the PR discussion slightly 😄

2017-04-18 09:21 UTC, dktapps submitted a review, later dismissed

2017-04-18 09:21 UTC, dktapps commented on src/pocketmine/Player.php
> +	 * @param strint $subtitle
Typo

2017-04-18 09:21 UTC, dktapps commented on src/pocketmine/Player.php
> +	public function addSubTitle(string $subtitle){
See my comments in the discussion about this method.

2017-04-18 09:24 UTC, TheDiamondYT1 commented on src/pocketmine/Player.php
> +	public function addSubTitle(string $subtitle){
It has to be a seperate method because i called addTitle( "" , "subtitle"); and it showed a blank title with the subtitle, which shouldnt happen

2017-04-18 09:27 UTC, dktapps commented on src/pocketmine/Player.php
> +	public function addSubTitle(string $subtitle){
Ah, I see. My bad.

2017-04-18 11:18 UTC, Sandertv commented on src/pocketmine/Player.php
> +	 * @param strint $subtitle
That's not a typo, @dktapps. It's a combination of a string and an integer :D

2017-04-18 12:49 UTC, dktapps commented
Looks good, will re-review after I test. My local working directory is full of light-population code mess at the moment, so I can't test this immediately.

2017-04-19 05:58 UTC, TheDiamondYT1 commented
@dktapps Maybe I could just add a `$immediate = false` to `addTitle()` then if its true, sender the title packet and if false it doesn't.

2017-04-19 21:44 UTC, TheDiamondYT1 commented
Bump

2017-04-20 17:10 UTC, dktapps commented
I derped when playing with /title and attempted to use /title d duration instead of /title d times. A case statement would be more suitable.

2017-04-20 17:15 UTC, Muqsit commented on src/pocketmine/command/defaults/TitleCommand.php
> +		if($args[1] === "clear"){
Maybe switch rather than multiple elseifs?

2017-04-20 17:16 UTC, dktapps requested changes

2017-04-20 17:16 UTC, dktapps commented on src/pocketmine/command/defaults/TitleCommand.php
> +		    $player->setTitleDuration($this->getInteger($sender, $args[3]), $this->getInteger($sender, $args[4]), $this->getInteger($sender, $args[5]));
These argument indices are incorrect. Player is 0, target is 1, fade-in should be 2, stay-time 3, fade-out 4. This causes unexpected behaviour when trying to add titles to a player.

2017-04-20 17:20 UTC, TheDiamondYT1 commented on src/pocketmine/command/defaults/TitleCommand.php
> +		if($args[1] === "clear"){
Yes, doing it.

2017-04-20 17:27 UTC, TheDiamondYT1 commented on src/pocketmine/command/defaults/TitleCommand.php
> +		    $player->setTitleDuration($this->getInteger($sender, $args[3]), $this->getInteger($sender, $args[4]), $this->getInteger($sender, $args[5]));
What do you mean? Player, target? Same thing?

2017-04-20 17:32 UTC, dktapps commented on src/pocketmine/command/defaults/TitleCommand.php
> +		    $player->setTitleDuration($this->getInteger($sender, $args[3]), $this->getInteger($sender, $args[4]), $this->getInteger($sender, $args[5]));
I meant subcommand, my bad. Don't know why I said that.

2017-04-20 17:40 UTC, dktapps commented on src/pocketmine/command/defaults/TitleCommand.php
> +		    $player->setTitleDuration($this->getInteger($sender, $args[3]), $this->getInteger($sender, $args[4]), $this->getInteger($sender, $args[5]));
To clarify, this occurs, and the duration number is used as fade-in, and the fade-out number is used as duration.
```
Notice: Undefined offset: 5 in src\pocketmine\command\defaults\TitleCommand.php on line 91
```

2017-04-20 18:48 UTC, Matthww commented
you're using spaces all over the place.

2017-04-20 18:57 UTC, TheDiamondYT1 commented
@Matthww Just following what the **other** command classes structure is like.

2017-04-20 18:57 UTC, TheDiamondYT1 commented
I will fix translations for all commands including this one in another PR.

2017-04-20 19:01 UTC, dktapps commented
Please use tabs instead of spaces, and strip trailing whitespace once you've finished making your changes.

2017-04-20 19:10 UTC, TheDiamondYT1 commented
I thought i was using tabs, it looks fine to me. I will remove whitespace but for some reason github viewer sometimes shows extra whitespaces.

2017-04-20 19:12 UTC, dktapps commented
There are a mixture of tabs and spaces, if you use your cursor to highlight parts of the diff you'll see what I mean.

2017-04-20 19:14 UTC, Matthww commented
![aee7bfdee8f8d8db9e338e7651b69d1d](https://cloud.githubusercontent.com/assets/3885070/25248372/533e4be2-260e-11e7-834e-6410f96d99aa.gif)

2017-04-20 19:15 UTC, TheDiamondYT1 commented
Yeah, well, - here's the thing. Im on an Android device because my computer has been acting up lately. I coded this whole PR on my device.

2017-04-20 22:14 UTC, jasonwynn10 commented
🤦‍♂️ Doing PRs without an IDE is SO unprofessional. Let alone only using github's editor!

2017-04-20 22:16 UTC, TheDiamondYT1 commented
@jasonwynn10 Im using an IDE, just not a PHP one :P

GitHub's editor doesnt work on my kindle fire.

2017-04-21 08:57 UTC, dktapps commented
@jasonwynn10 I wrote the new chunk implementation for the 1.0 update on my phone, is that unprofessional too? ;P

As long as the end result is OK, it doesn't matter too much how you got there. Just as long as everyone understands that it is _wiser_ to use a computer and a smart IDE. I discourage use of mobile devices though.

2017-04-22 14:02 UTC, TheDiamondYT1 commented
@dktapps I use a Terminal Emulator called Termux. It has the full git in its package manager.

And i use a Java IDE (😂) called AIDE for php.

2017-04-22 14:04 UTC, dktapps commented
Termux is a good solution, yea. I use it a lot.

2017-04-22 14:05 UTC, TheDiamondYT1 commented
@dktapps What IDE do you use?

*Apologizes for being off topic*

2017-04-22 14:11 UTC, dktapps commented
@TheDiamondYT1 I use QuickEdit for my editing needs, I don't tend to write actual code on mobile these days. I don't like AIDE and haven't found any other suitable editors or IDEs.

2017-04-25 20:33 UTC, TheDiamondYT1 commented
Bump

2017-04-25 21:10 UTC, dktapps commented
Will review tomorrow morning.

2017-04-27 15:40 UTC, dktapps commented
I had to reformat this locally, merged it to master as https://github.com/pmmp/PocketMine-MP/commit/653b6b55a9ab44d24e9402d0a253b3d394c62908

2017-04-27 15:40 UTC, closed without merging

2017-04-27 15:47 UTC, TheDiamondYT1 commented
Yeah sorry for the formatting. I edited AIDE to use spaces instead of tabs so i dont get a mixture in future PRs.

2017-04-28 14:16 UTC, SalmonDE commented
And you didn't add `Server::broadcastTitle()`? Is there a reason why this wasn't added?