Return class specification
pmmp/PocketMine-MP pull request #864
Opened 2017-04-24 17:13 UTC by opkiler22789

Result:
![2017-04-24_20-11-05](https://cloud.githubusercontent.com/assets/17113289/25349412/6e147c6a-292a-11e7-8505-2303b972bb1d.gif)

2017-04-24 17:26 UTC, TheDiamondYT1 commented on src/pocketmine/event/server/DataPacketReceiveEvent.php
> +	 /**
Terrible formatting for such a simple fix...

2017-04-24 17:31 UTC, Sandertv requested changes
I don't really see the point in only adding a PHP doc. Might be better if you'd add Typehints.

2017-04-24 18:14 UTC, Muqsit commented
Why a comment and not strict mode?

2017-04-24 18:16 UTC, opkiler22789 commented
@Muqsit, Sorry, but I do not know these little things

2017-04-24 18:20 UTC, madecode15 commented
@Muqsit @opkiler22789 How are coding a plugin if you don't know how to type hint?

2017-04-24 18:24 UTC, TheDiamondYT1 commented
@madecode15 its simple lol. But typehinting is good

2017-04-24 19:18 UTC, TheDiamondYT1 commented
Im about to make a pr to typehint all events

2017-04-25 02:30 UTC, SOF3 requested changes
Considering that network branch is being rewritten, it's not meaningful to add this here right now. Moreover, PhpStorm can detect the field type from the constructor assignment of the field.

2017-04-25 15:04 UTC, closed without merging