Use json_decode for effects data
pmmp/PocketMine-MP pull request #898
Opened 2017-05-07 15:40 UTC by TheDiamondYT1

## Introduction

Matches [this commit](https://github.com/pmmp/PocketMine-MP/commit/fe4322bea957b422ea8596712ccaf022a388c9b7#diff-c0f9e4f47d9a1ae7abba9ce1d681fd89R86) (OCD)

2017-05-07 15:44 UTC, dktapps requested changes

2017-05-07 15:44 UTC, dktapps commented on src/pocketmine/entity/Effect.php
> +		foreach($data as $name => $data){
Bad move.

2017-05-07 15:46 UTC, dktapps commented on src/pocketmine/entity/Effect.php
> +		foreach($data as $name => $data){
(lucky PhpStorm spotted this, I almost merged this without looking >_>)

2017-05-07 15:48 UTC, TheDiamondYT1 commented on src/pocketmine/entity/Effect.php
> +		foreach($data as $name => $data){
What is wrong?

2017-05-07 15:49 UTC, TheDiamondYT1 commented on src/pocketmine/entity/Effect.php
> +		foreach($data as $name => $data){
Oh..im so dumb

2017-05-07 15:52 UTC, TheDiamondYT1 commented
Sorry about that @dktapps. Im actually using IntelliJ... :rofl:

2017-05-08 16:56 UTC, dktapps approved these changes

2017-05-08 16:57 UTC, merged