Added short-hand Event->call() for easier event calling
pmmp/PocketMine-MP pull request #916
Opened 2017-05-14 11:22 UTC by dktapps

## Introduction
`$this->server->getPluginManager()->callEvent($ev)` is long and annoying. `$ev->call()` is a much nicer and quicker short-form that can now be used as an alternative.

## Changes
### API changes
- Added `Event->call()` which can be substituted for long `blah->getBlah()->getBlah()->getServer()->getPluginManager()->...`

## Backwards compatibility
No BC breaks, only API additions.

2017-05-14 11:25 UTC, TheDiamondYT1 commented
Maybe deprecate `PluginManager->callEvent()`?

2017-05-14 11:25 UTC, dktapps commented
No, this is simply syntactic sugar for developers.

2017-05-14 11:26 UTC, TheDiamondYT1 commented
@dktapps Okay

2017-05-14 13:38 UTC, SOF3 requested changes

2017-05-14 13:38 UTC, SOF3 commented on src/pocketmine/Player.php
>  		if($ev->isCancelled()){
What about also returning isCancelled() in the return value, or a constant `false` if the event is not a Cancellable?

2017-05-14 13:41 UTC, SOF3 approved these changes

2017-05-27 16:34 UTC, TheDiamondYT1 commented
When will this be merged?

2017-06-03 03:10 UTC, SOF3 commented on src/pocketmine/Player.php
>  		if($ev->isCancelled()){
Then what about returning `$this`?

2017-09-14 15:50 UTC, dktapps commented
This syntax, while shorter, is more ugly than the current approach. This branch also has conflicts with master that I have no interest in resolving, so I'm going to close it.

2017-09-14 15:50 UTC, closed without merging

2017-09-14 16:50 UTC, jasonwynn10 commented
:frowning: