Add EndRod
pmmp/PocketMine-MP pull request #940
Opened 2017-05-25 11:58 UTC by thebigsmileXD

## Introduction

It adds end rods as decoration and light source
Supports vanilla-like rotation and exact same placement

### Relevant issues

## Changes
### API changes

### Behavioural changes

new block  ¯\_(ツ)_/¯

## Backwards compatibility

## Follow-up

## Tests

Tested and used since month in a fork. No issues known

2017-05-25 12:54 UTC, jasonw4331 requested changes

2017-05-25 12:54 UTC, jasonwynn10 commented on src/pocketmine/block/EndRod.php
> +			[$this->id, 0, 1],
this needs changed according to 00afc5c363c8e54fd8f82dfdb3a3bff76672de9d

2017-05-25 12:59 UTC, dktapps requested changes
This causes players to be kicked for flying when walking on top of end-rods. Also see @jasonwynn10 's comment about the drops.

2017-05-25 15:25 UTC, thebigsmileXD commented on src/pocketmine/block/EndRod.php
> +			[$this->id, 0, 1],
i see

2017-05-25 15:26 UTC, thebigsmileXD commented
@dktapps "This", what exactly, i can't see it for a strange reason

2017-05-25 16:27 UTC, TheDiamondYT1 commented
If i were you @dktapps i wouldnt accept block pull requests untill the new json system is in place

2017-05-25 19:07 UTC, jasonw4331 requested changes

2017-05-25 19:07 UTC, jasonwynn10 commented on src/pocketmine/block/EndRod.php
> +class EndRod extends Flowable{
Shouldn't extend flowable

2017-05-25 19:08 UTC, jasonwynn10 commented
@TheDiamondYT1 this is a PR on the api3/blocks branch, so it will be added with everything else in the rewrite.

2017-05-28 12:56 UTC, thebigsmileXD commented
Bounding box fixed.

2017-05-28 13:48 UTC, thebigsmileXD commented
Opening a new PR due to git/github issues

2017-05-28 13:48 UTC, closed without merging